const heldReason=(x:any)=>x?.status==='HELD_NO_JOINT_MODEL'?'依存関係またはjoint modelが未確立のため、現在は数値推測に使用しません。':String(x?.status??'未解決');
const toUi=(projection:any)=>{const src=projection.runtimeUi;const sections=(src.evidenceSections??[]).map((s:any)=>({id:s.id,title:s.title,collapsible:s.collapsible!==false,defaultExpanded:s.defaultExpanded===true,descriptionPresentation:s.descriptionPresentation??{collapsible:true,label:'説明',defaultExpanded:false},items:(s.evidenceItems??[]).map((e:any)=>({id:'REF_'+e.findingId,evidenceId:e.findingId,label:e.label}))}));return {schemaVersion:'v8.5-runtime-ui-v1',contractVersion:'runtime-ui-v8',source:'CANONICAL_UI',sourceSchemaVersion:src.schemaVersion,manifestRevision:'8.5',accordion:{enabled:true,singleOpen:true},quickInput:{enabled:false},v8Sections:sections}};
export function buildAppRuntime(projection:any,projectionArtifact:any){
 if((projection.activeFeatures??[]).length>0||(projection.inactiveFeatures??[]).length>0)throw new Error('APP_RUNTIME_FEATURE_ADAPTER_NOT_IMPLEMENTED');
 if(projection.settings?.status!=='SOURCE_DERIVED'||!(projection.settings?.values?.length>0))throw new Error('APP_RUNTIME_SETTINGS_REQUIRED');
 const version='8.5.0-'+projection.batchId;
 const held=projection.heldObservations??[],hld=projection.highLowDiscrimination;
 return {schemaVersion:'app-runtime-v1',manifestVersion:'8.5',batchId:projection.batchId,machineId:projection.machineId,machineName:projection.machineName,sourceArtifact:projectionArtifact,package:{schemaVersion:1,provenance:{manifestVersion:'8.5',generationPath:'V8_5_PRODUCTION_PIPELINE',legacyOracleUsed:false},machine:{schemaVersion:'2.0.0',machineId:projection.machineId,machineDataVersion:version,displayName:projection.machineName,modelName:projection.machineName,settings:projection.settings.values,packagePolicy:projection.packagePolicy},inputs:{schemaVersion:'2.0.0',inputs:[]},features:{version:'8.5-runtime',features:[],runtimeProjection:[]},evidence:{version:'8.5-runtime',evidences:[],references:projection.evidence??[]},ui:toUi(projection),metadata:{machineId:projection.machineId,displayName:projection.machineName,settings:projection.settings.values,settingsStatus:projection.settings.status},v8:{machineResearchSummary:{title:'この機種の設定推測について',adopted:[],notAdopted:held.map((x:any)=>({featureId:x.findingId,label:x.label,reason:heldReason(x)})),unresolved:hld?.status==='NOT_COMPUTED'?[{label:'高低判別精度',reason:hld.reason}]:[]}}}};
}
