import {RepoStore} from './core.ts';
import {initializeBatch} from './runtime.ts';
import {selectProductionBatch} from './production-order-selector.ts';
const s=new RepoStore(process.cwd());
const canonical=s.read<any>('..','machine-identity-metadata.json');
const snapshot=s.read<any>('distribution-order-snapshot.json');
const cursor='L_MAGIA_RECORD_RN',batchId='batch-20261007-008';
const scan=selectProductionBatch(canonical.machines,cursor,snapshot.entries);
const expected=['L_SMASLO_KAIJI_KYOEN_FJ','L_LOVEJOU3_M4','L_GOBLIN_SLAYER_RD','L_GODZILLA_NS','L_USHIO_TORA_HAKUMEN_VH','L_AMAZING_LIVE_PD','L_YOSHIMUNE_SC2','L_MAHJONG_MONOGATARI_S2','L_IDOLMASTER_MILLION_LIVE_HC','L_YOUJITSU_DE'];
if(JSON.stringify(scan.selected)!==JSON.stringify(expected))throw Error('USER_SELECTION_MISMATCH');
if(s.exists('batches',batchId))throw Error('BATCH_ALREADY_EXISTS');
const spec={batchId,manifestVersion:'8.5',waves:[{waveId:'wave-1',machineIds:scan.selected.slice(0,5)},{waveId:'wave-2',machineIds:scan.selected.slice(5)}]};
initializeBatch(s,spec);
s.write(s.read<any>('config','runtime-policy-v8.5.json'),'batches',batchId,'runtime-policy-config.json');
s.write({...scan,canonicalSourceBlobSha:'1d520303506b2738f0e8f92ee5f25e066647c8e4',distributionSourceCommit:snapshot.sourceCommit,records:snapshot.entries},'batches',batchId,'selection-gap-scan.json');
const order=s.read<any>('machine-production-order.json');
order.completedThroughMachineId=cursor;order.nextMachineId=scan.selected[0];order.nextSequence=scan.selected;
order.activeBatchId=batchId;order.gapRecoveryMachineIds=scan.gaps;order.recordedAt='2026-10-07';
order.rules=['Use source.machines array order exactly; never sort by date or alphabet.','Before each selection scan every available entry through cursor against version, manifest and production provenance.','Recover gaps before cursor advancement. Skip only explicitly withdrawn or intentionally excluded entries.','Source SHA changes require reconciliation by machineId.'];
order.notes='Batch #007 user DEVICE_QA PASS; Batch #008 recovers 3 gaps then continues after Magia Record. Cursor indicates completed forward traversal, gap list is authoritative outstanding work.';
s.write(order,'machine-production-order.json');
console.log(JSON.stringify({batchId,...scan}));
