const IMPORTANCE_LABELS=['主要','有力','補助','微小'] as const;
function importanceFor(score:number){return score>=20?'主要':score>=10?'有力':score>=5?'補助':'微小'}
function userFacingScoreUnavailableReason(raw:any){const reason=String(raw??'').trim();if(!reason||/opportunity model|research|exact exposure|denominator|benchmark/i.test(reason))return '基準遊技量7000Gでの判別力を算出するための観測条件が確定していないため算出できません。';return reason}
function scoreView(e:any){const s=e?.metrics?.selectionScore;if(s?.status==='COMPUTED'&&typeof s.value==='number'&&Number.isFinite(s.value)){const value=Number(s.value.toFixed(1));return {label:'設定判別スコア',status:'COMPUTED',value,precision:1,importance:importanceFor(value)}}const sourceReason=e?.benchmarkExposure?.reason??'基準遊技量に対応するexact exposure modelが未確立のため算出しない。';const reason=userFacingScoreUnavailableReason(sourceReason);return {label:'設定判別スコア',status:'NOT_COMPUTED',display:'算出不可',reason,sourceReason}}
function categoryLabels(distribution:any){const out:string[]=[];for(const v of Object.values(distribution??{})){if(v&&typeof v==='object'&&!Array.isArray(v)){for(const k of Object.keys(v))if(!out.includes(k))out.push(k);continue}if(typeof v!=='string')continue;for(const raw of v.split('/')){const label=raw.trim().replace(/[:\s]*[-+]?\d+(?:\.\d+)?%\s*$/,'').trim();if(label&&!out.includes(label))out.push(label)}}return out}
const safeKey=(s:string,i:number)=>`${i+1}_${s.replace(/[^A-Za-z0-9一-龠ぁ-んァ-ヶー＋+_-]+/g,'_')}`;
export function buildCanonicalUi(candidate:any,observation:any,evaluation:any,candidateArtifact:any,observationArtifact:any,evaluationArtifact:any){
 if(candidate.machineId!==observation.machineId||candidate.machineId!==evaluation.machineId)throw new Error('CANONICAL_UI_BUILD_IDENTITY');
 const cBy=new Map((candidate.candidates??[]).map((x:any)=>[x.findingId,x]));const eBy=new Map((evaluation.evaluations??[]).map((x:any)=>[x.findingId,x]));
 const numericSections=(observation.observations??[]).filter((o:any)=>o.observationStatus==='READY').map((o:any)=>{const c:any=cBy.get(o.findingId),e:any=eBy.get(o.findingId);if(!c||!e||c.runtimeInferenceAllowed!==true||o.runtimeInferenceAllowed!==true)throw new Error('CANONICAL_UI_READY_SOURCE:'+o.findingId);let inputs:any[]=[];if(o.collectionContract?.type==='SUCCESS_TRIAL_COUNTS'){inputs=[{id:`${o.findingId}.${o.collectionContract.trialField}`,label:'観測機会数',role:'trial',mode:'NUMBER',directNumeric:true,quickAdd:[50],partialInputAllowed:true,emptyMeansUnobserved:true},{id:`${o.findingId}.${o.collectionContract.successField}`,label:'該当回数',role:'success',mode:'NUMBER',directNumeric:true,quickAdd:[1],partialInputAllowed:true,emptyMeansUnobserved:true,missingSubItemTreatment:'ZERO_WHEN_PARENT_OBSERVED'}]}else if(o.collectionContract?.type==='CATEGORY_COUNTS'){const labels=categoryLabels(c.settingDistribution);if(e.categoryModel?.residualPolicy==='SOURCE_EXPLICIT_OTHER'&&!labels.includes('その他'))labels.push('その他');if(labels.length<2)throw new Error('CANONICAL_UI_CATEGORIES_UNRESOLVED:'+o.findingId);inputs=[{id:`${o.findingId}.${o.collectionContract.trialField}`,label:'観測機会数',role:'trial',mode:'NUMBER',directNumeric:true,quickAdd:[50],partialInputAllowed:true,emptyMeansUnobserved:true},...labels.map((label:string,i:number)=>({id:`${o.findingId}.${o.collectionContract.countsField}.${safeKey(label,i)}`,label,role:'categoryCount',mode:'NUMBER',directNumeric:true,quickAdd:[1],partialInputAllowed:true,emptyMeansUnobserved:true,missingSubItemTreatment:'ZERO_WHEN_PARENT_OBSERVED'}))]}else throw new Error('CANONICAL_UI_COLLECTION_UNSUPPORTED:'+o.findingId);return {id:`OBS_${o.findingId}`,sourceFindingId:o.findingId,title:o.label,kind:'NUMERIC_OBSERVATION',model:o.model,trialUniverse:o.trialUniverse,collapsible:true,defaultExpanded:false,descriptionPresentation:{collapsible:true,label:'説明',defaultExpanded:false},score:scoreView(e),perEligibleTrialPower:{label:'1回の判別力',value:c.runtimePolicyBinding.value,metric:'PER_ELIGIBLE_TRIAL_POWER',thresholdSource:'RUNTIME_POLICY'},inputs}});
 const trialUniverses=new Set(numericSections.map((x:any)=>String(x.trialUniverse)));const totalOnlyUniverses=new Set(['TOTAL_GAME_TRIAL','LOTIS_NON_CHAIN_GAME_TRIAL','NON_CHAIN_BONUS_INITIAL_GAME_TRIAL']);const playInfoMode=trialUniverses.size>0&&[...trialUniverses].every(x=>totalOnlyUniverses.has(x))?'TOTAL_ONLY':'TOTAL_AND_NORMAL';const needsExcludedGames=[...trialUniverses].some(x=>['LOTIS_NON_CHAIN_GAME_TRIAL','NON_CHAIN_BONUS_INITIAL_GAME_TRIAL'].includes(x));
 const evidenceSections=(observation.evidence??[]).map((x:any)=>{const details=Array.isArray(x.details)?x.details.filter((v:any)=>typeof v==='string'&&v.trim()):[];const description=details.length?details.join('\n'):'設定示唆として確認できる項目です。数値による設定推測とは別に、実戦時の判断材料として参照できます。';return {id:`EVI_${x.findingId}`,sourceFindingId:x.findingId,title:x.label,kind:'EVIDENCE',collapsible:true,defaultExpanded:false,description,descriptionPresentation:{collapsible:true,label:'説明',defaultExpanded:false},runtimePolicyControlled:false,evidenceItems:[{findingId:x.findingId,label:x.label,sourceIds:x.sourceIds??[],details,semanticType:x.semanticType,semanticCategories:x.semanticCategories,settingDistribution:x.settingDistribution,runtimePolicyControlled:false,status:x.status,interaction:'REFERENCE_ONLY'}]}});
 const heldObservations=(observation.observations??[]).filter((o:any)=>o.observationStatus==='HELD_NO_JOINT_MODEL').map((o:any)=>({findingId:o.findingId,label:o.label,status:o.observationStatus,materialized:false}));
 return {schemaVersion:'canonical-ui-v1',manifestVersion:'8.5',batchId:candidate.batchId,machineId:candidate.machineId,machineName:candidate.machineName,sourceArtifacts:{candidateContract:candidateArtifact,observationEvidence:observationArtifact,evaluation:evaluationArtifact},machineInferenceSummary:{title:'この機種の設定推測について',position:'TOP_ONLY',highLowDiscrimination:observation.highLowDiscrimination},playInfo:{visible:true,collapsible:false,mode:playInfoMode,sessionFields:[{id:'date',label:'日付',mode:'DATE'},{id:'storeName',label:'店舗名',mode:'TEXT'},{id:'machineNumber',label:'台番号',mode:'TEXT'}],startFields:[{id:'startTotalGames',label:'着席時 総ゲーム数',mode:'NUMBER',directNumeric:true},...(playInfoMode==='TOTAL_AND_NORMAL'?[{id:'startNormalGames',label:'着席時 通常ゲーム数',mode:'NUMBER',directNumeric:true}]:[])],currentFields:[{id:'currentTotalGames',label:'現在 総ゲーム数',mode:'NUMBER',directNumeric:true},...(playInfoMode==='TOTAL_AND_NORMAL'?[{id:'currentNormalGames',label:'現在 通常ゲーム数',mode:'NUMBER',directNumeric:true}]:[])],difference:{autoCalculate:true},useDifference:{label:'着席時との差分を使用',defaultWhenStartNormalGamesPresent:true},...(needsExcludedGames?{exclusionGames:{visible:true,label:'除外ゲーム数（連荘中のゲーム数）'}}:{})},accordion:{enabled:true,singleOpen:true},numericSections,evidenceSections,heldObservations,layoutRules:{hideEmptySections:true,twoColumnWhen:{minimumNumericSections:2,minimumEvidenceSections:2},quickAddPolicy:[1,50],directNumericRequired:true},inputRules:{partialInputAllowed:true,missingSubItemTreatment:'ZERO_WHEN_PARENT_OBSERVED'},importanceVocabulary:[...IMPORTANCE_LABELS]};
}
