export const CANONICAL_UI_VALIDATOR_CONTRACT='canonical-ui-v1';
const canonical=(v:any):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')}}`:JSON.stringify(v);
const fail=(m:string):never=>{throw new Error('CANONICAL_UI_VALIDATION_FAILED:'+m)};const ALLOWED=new Set(['主要','有力','補助','微小']);
function importanceFor(score:number){return score>=20?'主要':score>=10?'有力':score>=5?'補助':'微小'}
function scoreExpected(e:any){const s=e?.metrics?.selectionScore;if(s?.status==='COMPUTED'&&typeof s.value==='number'&&Number.isFinite(s.value)){const value=Number(s.value.toFixed(1));return {label:'設定判別スコア',status:'COMPUTED',value,precision:1,importance:importanceFor(value)}}return {label:'設定判別スコア',status:'NOT_COMPUTED',display:'算出不可',reason:e?.benchmarkExposure?.reason??'基準遊技量に対応するexact exposure modelが未確立のため算出しない。'}}
function categoryLabels(distribution:any){const out:string[]=[];for(const v of Object.values(distribution??{})){if(v&&typeof v==='object'&&!Array.isArray(v)){for(const k of Object.keys(v))if(!out.includes(k))out.push(k);continue}if(typeof v!=='string')continue;for(const raw of v.split('/')){const label=raw.trim().replace(/[:\s]*[-+]?\d+(?:\.\d+)?%\s*$/,'').trim();if(label&&!out.includes(label))out.push(label)}}return out}
export function validateCanonicalUiDocument(doc:any,candidate:any,observation:any,evaluation:any,candidateArtifact:any,observationArtifact:any,evaluationArtifact:any){
 if(doc?.schemaVersion!=='canonical-ui-v1'||doc?.manifestVersion!=='8.5')fail('HEADER');if(doc.batchId!==candidate.batchId||doc.machineId!==candidate.machineId||doc.machineId!==observation.machineId||doc.machineId!==evaluation.machineId)fail('IDENTITY');if(canonical(doc.sourceArtifacts?.candidateContract)!==canonical(candidateArtifact)||canonical(doc.sourceArtifacts?.observationEvidence)!==canonical(observationArtifact)||canonical(doc.sourceArtifacts?.evaluation)!==canonical(evaluationArtifact))fail('LINKAGE');
 if(doc.machineInferenceSummary?.title!=='この機種の設定推測について'||doc.machineInferenceSummary?.position!=='TOP_ONLY')fail('SUMMARY');if(canonical(doc.machineInferenceSummary.highLowDiscrimination)!==canonical(observation.highLowDiscrimination))fail('HLD_COPY');if(doc.accordion?.enabled!==true||doc.accordion?.singleOpen!==true)fail('ACCORDION');
 const p=doc.playInfo;if(p?.visible!==true||p?.collapsible!==false||p?.difference?.autoCalculate!==true||p?.useDifference?.label!=='着席時との差分を使用'||p?.useDifference?.defaultWhenStartNormalGamesPresent!==true)fail('PLAY_INFO');const session=(p.sessionFields??[]).map((x:any)=>x.label),start=(p.startFields??[]).map((x:any)=>x.label),current=(p.currentFields??[]).map((x:any)=>x.label);if(canonical(session)!==canonical(['日付','店舗名','台番号'])||canonical(start)!==canonical(['着席時 総ゲーム数','着席時 通常ゲーム数'])||canonical(current)!==canonical(['現在 総ゲーム数','現在 通常ゲーム数']))fail('PLAY_FIELDS');
 if(!Array.isArray(doc.numericSections)||!Array.isArray(doc.evidenceSections)||!Array.isArray(doc.heldObservations))fail('ARRAYS');const ready=(observation.observations??[]).filter((x:any)=>x.observationStatus==='READY'),held=(observation.observations??[]).filter((x:any)=>x.observationStatus==='HELD_NO_JOINT_MODEL');if(doc.numericSections.length!==ready.length)fail('NUMERIC_COVERAGE');if(doc.evidenceSections.length!==(observation.evidence??[]).length)fail('EVIDENCE_COVERAGE');if(doc.heldObservations.length!==held.length)fail('HELD_COVERAGE');
 const cBy=new Map((candidate.candidates??[]).map((x:any)=>[x.findingId,x])),eBy=new Map((evaluation.evaluations??[]).map((x:any)=>[x.findingId,x])),nBy=new Map(doc.numericSections.map((x:any)=>[x.sourceFindingId,x]));
 for(const o of ready){const s:any=nBy.get(o.findingId),c:any=cBy.get(o.findingId),e:any=eBy.get(o.findingId);if(!s||!c||!e)fail('NUMERIC_SOURCE:'+o.findingId);if(s.title!==o.label||s.kind!=='NUMERIC_OBSERVATION'||s.model!==o.model||s.trialUniverse!==o.trialUniverse||c.runtimeInferenceAllowed!==true||o.runtimeInferenceAllowed!==true)fail('NUMERIC_COPY:'+o.findingId);if(!Array.isArray(s.inputs)||s.inputs.length===0)fail('EMPTY_SECTION:'+o.findingId);if(canonical(s.score)!==canonical(scoreExpected(e)))fail('SCORE:'+o.findingId);if(s.score?.importance&&!ALLOWED.has(s.score.importance))fail('IMPORTANCE:'+o.findingId);if(s.perEligibleTrialPower?.label!=='1回の判別力'||s.perEligibleTrialPower?.metric!=='PER_ELIGIBLE_TRIAL_POWER'||s.perEligibleTrialPower?.value!==c.runtimePolicyBinding?.value)fail('POWER:'+o.findingId);if(s.inputs.some((x:any)=>x.mode!=='NUMBER'||x.directNumeric!==true||!Array.isArray(x.quickAdd)||x.quickAdd.some((q:any)=>![1,50].includes(q))))fail('INPUT_CONTRACT:'+o.findingId);if(o.collectionContract?.type==='SUCCESS_TRIAL_COUNTS'){const ids=s.inputs.map((x:any)=>x.id);if(canonical(ids)!==canonical([o.collectionContract.trialField,o.collectionContract.successField])||s.inputs[0].quickAdd[0]!==50||s.inputs[1].quickAdd[0]!==1)fail('BERNOULLI_INPUT:'+o.findingId)}else if(o.collectionContract?.type==='CATEGORY_COUNTS'){const labels=categoryLabels(c.settingDistribution);if(e.categoryModel?.residualPolicy==='SOURCE_EXPLICIT_OTHER'&&!labels.includes('その他'))labels.push('その他');if(labels.length<2||!o.collectionContract?.trialField||canonical(s.inputs.map((x:any)=>x.label))!==canonical(['観測機会数',...labels])||s.inputs[0]?.id!==o.collectionContract.trialField||s.inputs[0]?.quickAdd?.[0]!==50||s.inputs.slice(1).some((x:any)=>x.quickAdd?.[0]!==1))fail('CATEGORY_INPUT:'+o.findingId)}else fail('COLLECTION:'+o.findingId)}
 const hBy=new Map(doc.heldObservations.map((x:any)=>[x.findingId,x]));for(const o of held){const h:any=hBy.get(o.findingId);if(!h||h.status!=='HELD_NO_JOINT_MODEL'||h.materialized!==false)fail('HELD:'+o.findingId);if(nBy.has(o.findingId))fail('HELD_MATERIALIZED:'+o.findingId)}
 const evBy=new Map(doc.evidenceSections.map((x:any)=>[x.sourceFindingId,x]));for(const e of observation.evidence??[]){const s:any=evBy.get(e.findingId);if(!s||s.title!==e.label||s.kind!=='EVIDENCE'||s.runtimePolicyControlled!==false||!Array.isArray(s.evidenceItems)||s.evidenceItems.length!==1)fail('EVIDENCE:'+e.findingId);const i=s.evidenceItems[0];if(i.findingId!==e.findingId||i.label!==e.label||canonical(i.sourceIds)!==canonical(e.sourceIds??[])||i.status!==e.status||i.interaction!=='REFERENCE_ONLY')fail('EVIDENCE_COPY:'+e.findingId)}
 const allTitles=[...doc.numericSections,...doc.evidenceSections].map((x:any)=>x.title);if(allTitles.includes('この機種の設定推測について'))fail('SUMMARY_DUPLICATE');if(doc.layoutRules?.hideEmptySections!==true||canonical(doc.layoutRules?.quickAddPolicy)!==canonical([1,50])||doc.layoutRules?.directNumericRequired!==true)fail('LAYOUT');if(canonical(doc.importanceVocabulary)!==canonical(['主要','有力','補助','微小']))fail('IMPORTANCE_VOCABULARY');if(doc.evidenceSections.some((x:any)=>x.runtimePolicyControlled!==false))fail('EVIDENCE_RUNTIME_POLICY');
 return [{validator:CANONICAL_UI_VALIDATOR_CONTRACT,numericSections:ready.length,evidenceSections:(observation.evidence??[]).length,heldObservations:held.length}];
}
export function validateCanonicalUiArtifacts(s:any,a:any,r:any){const out=r.producedArtifacts??[];if(out.length!==1)fail('OUTPUT_COUNT');const ref=out[0];if(ref.kind!=='canonical-ui'||typeof ref.path!=='string'||!ref.path.startsWith(`production/batches/${a.batchId}/artifacts/${a.machineId}/canonical_ui/`))fail('OUTPUT_REF');const prefix='production/';const doc=s.read(...ref.path.slice(prefix.length).split('/'));const cs=s.read('batches',a.batchId,'machines',a.machineId,'stages','CANDIDATE_CONTRACT.json'),os=s.read('batches',a.batchId,'machines',a.machineId,'stages','OBSERVATION_EVIDENCE.json'),es=s.read('batches',a.batchId,'machines',a.machineId,'stages','EVALUATION.json');if(!cs.authoritativeOutputRef?.path||!os.authoritativeOutputRef?.path||!es.authoritativeOutputRef?.path)fail('UPSTREAM_AUTHORITY_MISSING');const candidate=s.read(...String(cs.authoritativeOutputRef.path).slice(prefix.length).split('/')),observation=s.read(...String(os.authoritativeOutputRef.path).slice(prefix.length).split('/')),evaluation=s.read(...String(es.authoritativeOutputRef.path).slice(prefix.length).split('/'));if(observation.candidateContractArtifact?.path!==cs.authoritativeOutputRef.path)fail('OBSERVATION_CANDIDATE_LINK');return validateCanonicalUiDocument(doc,candidate,observation,evaluation,cs.authoritativeOutputRef,os.authoritativeOutputRef,es.authoritativeOutputRef)}
