import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
export type StageState='PENDING'|'READY'|'LEASED'|'RUNNING'|'VALIDATING'|'WAIT_EXTERNAL'|'HUMAN_REQUIRED'|'RETRY_WAIT'|'FAILED'|'COMPLETE';
export type WorkerStatus='SUCCESS'|'FAILED_RETRYABLE'|'FAILED_TERMINAL'|'WAIT_EXTERNAL'|'HUMAN_REQUIRED';
export interface Stage {batchId:string;machineId:string;name:string;state:StageState;revision:number;dependencies:string[];activeAttemptId?:string;activeLeaseId?:string;authoritativeOutputRef?:any;authoritativeInputFingerprint:string;contractVersion:string;retryNotBefore?:string;humanResolved?:boolean;externalResolved?:boolean}
export interface Attempt {attemptId:string;workId:string;batchId:string;machineId:string;stage:string;number:number;inputFingerprint:string;contractVersion:string;createdAt:string;status:'ACTIVE'|'FAILED'|'COMPLETE'}
export interface Lease {leaseId:string;workId:string;attemptId:string;batchId:string;machineId:string;stage:string;leaseGeneration:number;inputFingerprint:string;contractVersion:string;acquiredAt:string;heartbeatAt:string;expiresAt:string;status:'ACTIVE'|'RELEASED'|'EXPIRED'|'REVOKED'}
export interface WorkRequest {workId:string;attemptId:string;batchId:string;machineId:string;stage:string;workType:string;workerType:string;contractVersion:string;manifestVersion:string;validatorContractVersion:string;authoritativeInputFingerprint:string;inputArtifacts:any[];allowedMutationScope:any[];forbiddenMutationScope:any[];expectedOutputs:any[];leaseId:string;leaseGeneration:number;leaseExpiresAt:string}
export interface WorkResult {workId:string;attemptId:string;leaseId:string;leaseGeneration:number;status:WorkerStatus;observedInputFingerprint:string;producedArtifacts:any[];validationEvidence:any[];requestedActions:any[];proposedNextState?:StageState;provenance:any}
export interface Transition {transitionId:string;batchId:string;machineId:string;stage:string;fromState:StageState;toState:StageState;causeType:string;causeId:string;expectedRevision:number;committedRevision:number;committedAt:string;orchestratorContractVersion:string}
export const LEGAL:Record<StageState,StageState[]>={PENDING:['READY'],READY:['LEASED'],LEASED:['RUNNING','READY'],RUNNING:['VALIDATING','WAIT_EXTERNAL','HUMAN_REQUIRED','RETRY_WAIT','FAILED'],VALIDATING:['COMPLETE','RETRY_WAIT','FAILED'],WAIT_EXTERNAL:['READY'],HUMAN_REQUIRED:['READY'],RETRY_WAIT:['READY'],FAILED:[],COMPLETE:['READY']};
export const canonical=(v:any):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')}}`:JSON.stringify(v);
export const fingerprint=(v:any)=>crypto.createHash('sha256').update(canonical(v)).digest('hex');
export const id=(p:string)=>`${p}_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`;
export class RepoStore { root:string; constructor(root:string){this.root=root} p(...x:string[]){return path.join(this.root,...x)} read<T>(...x:string[]):T{return JSON.parse(fs.readFileSync(this.p(...x),'utf8'))} write(v:any,...x:string[]){const f=this.p(...x);fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,f)} exists(...x:string[]){return fs.existsSync(this.p(...x))} append(v:any,...x:string[]){const f=this.p(...x);fs.mkdirSync(path.dirname(f),{recursive:true});fs.appendFileSync(f,JSON.stringify(v)+'\n')} }
export class Orchestrator {
 s:RepoStore; now:()=>Date; contract:string; constructor(s:RepoStore,now=()=>new Date(),contract='orch-1'){this.s=s;this.now=now;this.contract=contract}
 stage(b:string,m:string,n:string){return this.s.read<Stage>('batches',b,'machines',m,'stages',n+'.json')}
 validateStageShape(x:any){const states=Object.keys(LEGAL);if(!x||typeof x.batchId!=='string'||typeof x.machineId!=='string'||typeof x.name!=='string'||!states.includes(x.state)||!Number.isInteger(x.revision)||!Array.isArray(x.dependencies)||typeof x.authoritativeInputFingerprint!=='string'||typeof x.contractVersion!=='string')throw new Error('SCHEMA_INVALID_STAGE');return x as Stage}
 saveStage(x:Stage){this.validateStageShape(x);this.s.write(x,'batches',x.batchId,'machines',x.machineId,'stages',x.name+'.json')}
 transition(x:Stage,to:StageState,causeType:string,causeId:string,expected=x.revision){if(x.revision!==expected)throw new Error('CAS_CONFLICT');if(!LEGAL[x.state].includes(to))throw new Error(`ILLEGAL_TRANSITION:${x.state}->${to}`);if(x.state==='COMPLETE'&&to==='READY'&&causeType!=='AUTHORITATIVE_OUTPUT_INVALIDATED')throw new Error('INVALID_REPAIR_TRANSITION');const from=x.state;x={...x,state:to,revision:x.revision+1};this.saveStage(x);const t:Transition={transitionId:id('trn'),batchId:x.batchId,machineId:x.machineId,stage:x.name,fromState:from,toState:to,causeType,causeId,expectedRevision:expected,committedRevision:x.revision,committedAt:this.now().toISOString(),orchestratorContractVersion:this.contract};this.s.append(t,'batches',x.batchId,'transitions','history.jsonl');return x}
 reconcile(b:string,m:string,n:string){let x=this.stage(b,m,n);if(x.activeLeaseId){const l=this.s.read<Lease>('batches',b,'leases',x.activeLeaseId+'.json');if(l.status==='ACTIVE'&&Date.parse(l.expiresAt)<=this.now().getTime()){l.status='EXPIRED';this.s.write(l,'batches',b,'leases',l.leaseId+'.json');const a=this.findAttempt(b,l.attemptId);if(a){a.status='FAILED';this.s.write(a,'batches',b,'machines',a.machineId,'attempts',a.attemptId+'.json')}x.activeLeaseId=undefined;x.activeAttemptId=undefined;if(x.state==='RUNNING')x=this.transition(x,'RETRY_WAIT','LEASE_EXPIRED',l.leaseId);else if(x.state==='LEASED')x=this.transition(x,'READY','LEASE_EXPIRED',l.leaseId);else this.saveStage(x)}}if(x.state==='WAIT_EXTERNAL'&&x.externalResolved)x=this.transition(x,'READY','RECONCILE','external-resolved');if(x.state==='HUMAN_REQUIRED'&&x.humanResolved)x=this.transition(x,'READY','RECONCILE','human-decision');if(x.state==='RETRY_WAIT'&&(!x.retryNotBefore||Date.parse(x.retryNotBefore)<=this.now().getTime()))x=this.transition(x,'READY','RECONCILE','retry-ready');return x}
 createAttempt(x:Stage){const dir=this.s.p('batches',x.batchId,'machines',x.machineId,'attempts');fs.mkdirSync(dir,{recursive:true});const num=fs.readdirSync(dir).filter(f=>f.endsWith('.json')).length+1;const a:Attempt={attemptId:id('att'),workId:id('wrk'),batchId:x.batchId,machineId:x.machineId,stage:x.name,number:num,inputFingerprint:x.authoritativeInputFingerprint,contractVersion:x.contractVersion,createdAt:this.now().toISOString(),status:'ACTIVE'};this.s.write(a,'batches',x.batchId,'machines',x.machineId,'attempts',a.attemptId+'.json');return a}
 acquire(x:Stage,a:Attempt,ttl=60000){const ld=this.s.p('batches',x.batchId,'leases');fs.mkdirSync(ld,{recursive:true});for(const f of fs.readdirSync(ld).filter(f=>f.endsWith('.json'))){const l=this.s.read<Lease>('batches',x.batchId,'leases',f);if(l.machineId===x.machineId&&l.stage===x.name&&l.status==='ACTIVE'&&Date.parse(l.expiresAt)>this.now().getTime())throw new Error('ACTIVE_WRITER_EXISTS')};const old=fs.readdirSync(ld).filter(f=>f.endsWith('.json')).map(f=>this.s.read<Lease>('batches',x.batchId,'leases',f)).filter(l=>l.machineId===x.machineId&&l.stage===x.name);const gen=Math.max(0,...old.map(l=>l.leaseGeneration))+1;const at=this.now();const l:Lease={leaseId:id('lea'),workId:a.workId,attemptId:a.attemptId,batchId:x.batchId,machineId:x.machineId,stage:x.name,leaseGeneration:gen,inputFingerprint:a.inputFingerprint,contractVersion:a.contractVersion,acquiredAt:at.toISOString(),heartbeatAt:at.toISOString(),expiresAt:new Date(at.getTime()+ttl).toISOString(),status:'ACTIVE'};this.s.write(l,'batches',x.batchId,'leases',l.leaseId+'.json');x.activeAttemptId=a.attemptId;x.activeLeaseId=l.leaseId;this.saveStage(x);return l}
 expire(l:Lease){if(l.status==='ACTIVE'&&Date.parse(l.expiresAt)<=this.now().getTime()){l.status='EXPIRED';this.s.write(l,'batches',l.batchId,'leases',l.leaseId+'.json')}return l}
 request(x:Stage,a:Attempt,l:Lease):WorkRequest{return {workId:a.workId,attemptId:a.attemptId,batchId:x.batchId,machineId:x.machineId,stage:x.name,workType:x.name,workerType:'MOCK',contractVersion:x.contractVersion,manifestVersion:'8.5',validatorContractVersion:'mock-1',authoritativeInputFingerprint:x.authoritativeInputFingerprint,inputArtifacts:[],allowedMutationScope:[{repository:'data',pathPattern:`production/batches/${x.batchId}/**`,operations:['READ','CREATE','UPDATE']}],forbiddenMutationScope:[{operations:['DELETE']}],expectedOutputs:[],leaseId:l.leaseId,leaseGeneration:l.leaseGeneration,leaseExpiresAt:l.expiresAt}}
 validateResultShape(r:any){if(!r||typeof r.workId!=='string'||typeof r.attemptId!=='string'||typeof r.leaseId!=='string'||!Number.isInteger(r.leaseGeneration)||!['SUCCESS','FAILED_RETRYABLE','FAILED_TERMINAL','WAIT_EXTERNAL','HUMAN_REQUIRED'].includes(r.status)||typeof r.observedInputFingerprint!=='string'||!Array.isArray(r.producedArtifacts))throw new Error('SCHEMA_INVALID_WORK_RESULT');return r as WorkResult}
 accept(r:WorkResult){this.validateResultShape(r);const dup=this.s.p('batches',this.findBatch(r),'events','accepted-'+r.workId+'.json');if(fs.existsSync(dup))return {kind:'DUPLICATE'} as const;const b=this.findBatch(r),a=this.findAttempt(b,r.attemptId);if(!a||a.workId!==r.workId)return this.stale(b,r,'attempt/work mismatch');const l=this.s.read<Lease>('batches',b,'leases',r.leaseId+'.json');const x=this.stage(b,a.machineId,a.stage);if(l.attemptId!==r.attemptId||l.workId!==r.workId||l.leaseGeneration!==r.leaseGeneration||l.status!=='ACTIVE'||Date.parse(l.expiresAt)<=this.now().getTime()||x.activeLeaseId!==l.leaseId||x.activeAttemptId!==a.attemptId||x.authoritativeInputFingerprint!==r.observedInputFingerprint||x.contractVersion!==a.contractVersion)return this.stale(b,r,'lease/fingerprint/state stale');if(r.status==='SUCCESS'){let v=this.transition(x,'VALIDATING','WORK_RESULT',r.workId,x.revision); if(!this.validate(r)) return {kind:'VALIDATION_FAIL'} as const;
 const reloaded=this.stage(b,a.machineId,a.stage);const freshLease=this.s.read<Lease>('batches',b,'leases',r.leaseId+'.json');
 if(reloaded.revision!==v.revision||reloaded.activeLeaseId!==l.leaseId||reloaded.activeAttemptId!==a.attemptId||reloaded.authoritativeInputFingerprint!==r.observedInputFingerprint||freshLease.status!=='ACTIVE'||freshLease.leaseGeneration!==r.leaseGeneration)return this.stale(b,r,'COMPARE_AND_COMMIT_CONFLICT');
 if(r.producedArtifacts.length===1){reloaded.authoritativeOutputRef=r.producedArtifacts[0];this.saveStage(reloaded)}v=this.transition(reloaded,'COMPLETE','VALIDATOR',r.workId,reloaded.revision);a.status='COMPLETE';l.status='RELEASED';this.s.write(a,'batches',b,'machines',a.machineId,'attempts',a.attemptId+'.json');this.s.write(l,'batches',b,'leases',l.leaseId+'.json');this.s.write({workId:r.workId},'batches',b,'events','accepted-'+r.workId+'.json');return {kind:'COMMITTED',stage:v} as const}if(r.status==='FAILED_RETRYABLE'){a.status='FAILED';l.status='RELEASED';x.activeAttemptId=undefined;x.activeLeaseId=undefined;const v=this.transition(x,'RETRY_WAIT','WORK_RESULT',r.workId);this.s.write(a,'batches',b,'machines',a.machineId,'attempts',a.attemptId+'.json');this.s.write(l,'batches',b,'leases',l.leaseId+'.json');return {kind:'RETRY_WAIT',stage:v} as const}if(r.status==='WAIT_EXTERNAL'||r.status==='HUMAN_REQUIRED'||r.status==='FAILED_TERMINAL'){a.status=r.status==='FAILED_TERMINAL'?'FAILED':'COMPLETE';l.status='RELEASED';this.s.write(a,'batches',b,'machines',a.machineId,'attempts',a.attemptId+'.json');this.s.write(l,'batches',b,'leases',l.leaseId+'.json');x.activeAttemptId=undefined;x.activeLeaseId=undefined;if(r.status==='WAIT_EXTERNAL')return {kind:'WAIT_EXTERNAL',stage:this.transition(x,'WAIT_EXTERNAL','WORK_RESULT',r.workId)} as const;if(r.status==='HUMAN_REQUIRED')return {kind:'HUMAN_REQUIRED',stage:this.transition(x,'HUMAN_REQUIRED','WORK_RESULT',r.workId)} as const;return {kind:'FAILED',stage:this.transition(x,'FAILED','WORK_RESULT',r.workId)} as const}throw new Error('UNREACHABLE_STATUS')}
 validate(r:WorkResult){return r.producedArtifacts.every(a=>!String(a.path||'').includes('..'))}
 stale(b:string,r:WorkResult,reason:string){this.s.append({...r,reason,receivedAt:this.now().toISOString()},'batches',b,'events','stale-results.jsonl');return {kind:'STALE',reason} as const}
 findBatch(r:WorkResult){const bs=this.s.p('batches');for(const b of fs.readdirSync(bs)){if(this.findAttempt(b,r.attemptId))return b}throw new Error('UNKNOWN_WORK')}
 findAttempt(b:string,idv:string):Attempt|undefined{const md=this.s.p('batches',b,'machines');if(!fs.existsSync(md))return;for(const m of fs.readdirSync(md)){const f=this.s.p('batches',b,'machines',m,'attempts',idv+'.json');if(fs.existsSync(f))return JSON.parse(fs.readFileSync(f,'utf8'))}}
}
export class MockWorkerAdapter {execute(q:WorkRequest,status:WorkerStatus='SUCCESS'):WorkResult{return {workId:q.workId,attemptId:q.attemptId,leaseId:q.leaseId,leaseGeneration:q.leaseGeneration,status,observedInputFingerprint:q.authoritativeInputFingerprint,producedArtifacts:[],validationEvidence:[{validator:'mock'}],requestedActions:[],proposedNextState:'COMPLETE',provenance:{adapter:'mock'}}}}
export interface Concurrency {semanticSlots:number;productionSlots:number;validationSlots:number;integrationSlots:number}
export function dispatchable(x:Stage, all:Record<string,Stage>, now:Date, batchBlocking=false){return x.state==='READY'&&!batchBlocking&&x.dependencies.every(d=>all[d]?.state==='COMPLETE')&&(!x.retryNotBefore||Date.parse(x.retryNotBefore)<=now.getTime())&&!x.activeLeaseId}
export function schedule(stages:Stage[],all:Record<string,Stage>,slots:number,now:Date){return stages.filter(x=>dispatchable(x,all,now)).sort((a,b)=>a.machineId.localeCompare(b.machineId)||a.name.localeCompare(b.name)).slice(0,slots)}
export function renewLease(s:RepoStore,l:Lease,now:Date,ttl=60000){if(l.status!=='ACTIVE'||Date.parse(l.expiresAt)<=now.getTime())throw new Error('LEASE_NOT_RENEWABLE');l.heartbeatAt=now.toISOString();l.expiresAt=new Date(now.getTime()+ttl).toISOString();s.write(l,'batches',l.batchId,'leases',l.leaseId+'.json');return l}
