"""Reviewed, source-derived Batch008 findings; regenerate drafts without remote writes."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]/'batches'/'batch-20261007-008'
SPEC=json.load(open(BASE/'batch.json'))
QUERIES=json.load(open(BASE/'research-search-queries.json'))
DOMAINS=['INITIAL_HIT','BONUS','SMALL_ROLE','CZ','AT','INTERNAL_CONDITIONAL_DRAW','MODE_TRANSITION','STATE_TRANSITION','SUCCESS_RATE','POINTS_GAME_DISTRIBUTION','CARRY_OVER','THRESHOLD_BEHAVIOR','RESET_BEHAVIOR','POST_EVENT_TRANSITION','NAVIGATION','ROLE_CONDITIONAL_DISTRIBUTION','BONUS_TYPE_CONDITIONAL','EVIDENCE','EXTERNAL_DATA_ONLY','MACHINE_SPECIFIC']
X='EXACT_CONSTRAINT';P='PROBABILITY_UNKNOWN';D='DISPLAY_ONLY'
class Research:
 def __init__(self,index,name,url,title,settings=(1,2,3,4,5,6)):
  self.index=index;self.settings=settings;self.mid=sum([w['machineIds'] for w in SPEC['waves']],[])[index];self.wave=SPEC['waves'][index//5]['waveId'];self.ledger=[]
  self.d={'schemaVersion':'research-v1','manifestVersion':'8.5','batchId':SPEC['batchId'],'machineId':self.mid,'machineName':name,'researchedAt':'2026-10-07','settings':{'status':'SOURCE_DERIVED','values':['SET_'+str(i) for i in settings]},'sources':[],'findings':[],'blockedItems':[]}
  self.source('analysis',url,title)
 def source(self,sid,url,title,typ='primary_analysis'):
  self.d['sources'].append({'sourceId':sid,'url':url,'title':title,'sourceType':typ,'checkedAt':'2026-10-07','claims':[]})
 def trace(self,id,label,sids,disposition):
  claims=[]
  for sid in sids:
   src=next(s for s in self.d['sources'] if s['sourceId']==sid);claim=label+'の公開値・観測条件を確認';src['claims'].append(claim);claims.append({'sourceId':sid,'claim':claim})
  self.ledger.append({'candidateId':disposition['type'].lower()+':'+id,'label':label,'sourceClaims':claims,'discoveryQueries':[],'disposition':disposition})
 def fact(self,id,label,reason,sids=None):self.trace(id,label,sids or ['analysis'],{'type':'NO_SETTING_DIFFERENCE','reason':reason})
 def add(self,f):self.d['findings'].append(f);self.trace(f['findingId'],f['label'],f['sourceIds'],{'type':'FINDING','refId':f['findingId']});return f
 def num(self,id,label,values,scope,trial='NORMAL_GAME_TRIAL',conditional=False,sids=None,status='EXACT_WITH_SCOPE_TRACKING'):
  dist=dict(zip(map(str,self.settings),values));return self.add({'findingId':id,'label':label,'observationType':'conditional_probability' if conditional else 'probability','settingDistribution':dist,'sourceIds':sids or ['analysis'],'trialUniverse':trial,'denominatorSemantics':scope,'liveObservation':{'status':status,'reason':scope},'details':[]})
 def rates(self,id,label,denoms,scope,**kw):return self.num(id,label,['1/'+str(v) for v in denoms],scope,**kw)
 def category(self,id,label,labels,rows,trial,scope,sids=None,status='DIRECT_EXACT'):
  return self.add({'findingId':id,'label':label,'observationType':'appearance_distribution','settingDistribution':{str(i):' / '.join(f'{a} {b}%' for a,b in zip(labels,row)) for i,row in zip(self.settings,rows)},'sourceIds':sids or ['analysis'],'trialUniverse':trial,'denominatorSemantics':scope,'liveObservation':{'status':status,'reason':scope},'categoryModel':{'residualPolicy':'SOURCE_EXHAUSTIVE'},'details':[scope,'公表値の丸め誤差のみ補正し、未公表の設定値は補いません。']})
 def evidence(self,id,label,cats,sids=None,details=None):return self.add({'findingId':id,'label':label,'observationType':'evidence','sourceIds':sids or ['analysis'],'semanticCategories':[{'label':a,'meaning':b,'semanticType':t} for a,b,t in cats],'details':details or ['出現率は未公表です。設定が限定される表示だけを確定条件に使用し、それ以外は記録します。']})
 def block(self,id,label,reason,sids=None,raw=None):
  b={'blockId':id,'label':label,'reason':reason,'reevaluationCondition':'本機の全設定の数値と、対象の抽選条件・結果を正確に確認する方法が公表されること。','sourceIds':sids or ['analysis']}
  if raw is not None:b['rawSourceValues']=raw
  self.d['blockedItems'].append(b);self.trace(id,label,b['sourceIds'],{'type':'BLOCKED','refId':id})
 def dependent(self,ids,group,reason):
  for rank,id in enumerate(ids,1):
   f=next(f for f in self.d['findings'] if f['findingId']==id);f.update(dependencyGroupId=group,dependencyKind='CAUSAL_PATH_OVERLAP',dependencyReason=reason,dependencyFallbackRank=rank)
 def done(self,notes,na=()):
  for i,q in enumerate(QUERIES[self.index]):self.ledger[i%len(self.ledger)]['discoveryQueries'].append(q)
  default={'INITIAL_HIT':'通常初当たりと継続当たりの範囲を確認。','BONUS':'ボーナスの入口・継続・種別を機種概要で確認。','SMALL_ROLE':'公開小役値と、停止形・状態による違いを確認。','CZ':'CZの入口と成功抽選を確認。','AT':'ATの入口・継続・上位への経路を確認。','INTERNAL_CONDITIONAL_DRAW':'内部状態を外見で確定できない抽選を、確定した対象回数として数えない。','MODE_TRANSITION':'モード示唆と実際の内部モードを区別。未公開の設定別振り分けは推定しない。','STATE_TRANSITION':'ステージや前兆による示唆を内部状態の確定としない。','SUCCESS_RATE':'成功率と抽選対象回数を区別。全設定の値が揃わない候補は保留。','POINTS_GAME_DISTRIBUTION':'ゲーム数・ポイント・規定回数と当選の関係を確認。','CARRY_OVER':'継続・引き戻しを初当たりに混ぜない。','THRESHOLD_BEHAVIOR':'天井到達より前の当選から、選ばれた内部天井を逆算しない。','RESET_BEHAVIOR':'設定変更の恩恵と設定番号の判別を区別。','POST_EVENT_TRANSITION':'終了後の継続・引き戻しと通常初当たりを区別。','NAVIGATION':'押し順・告知操作と観測対象を確認。','ROLE_CONDITIONAL_DISTRIBUTION':'成立役ごとの抽選は、役・内部状態・履歴条件を限定して確認。','BONUS_TYPE_CONDITIONAL':'ボーナス種別を特定できる表示と内部選択を区別。','EVIDENCE':'本機で確認済みの確定条件と、確率不明の示唆を分離。','EXTERNAL_DATA_ONLY':'外部公開の機種解析を確認。内部抽選の完全な履歴として扱える情報は確認できない。','MACHINE_SPECIFIC':'機種固有の抽選・表示を検索し、該当候補を台帳に記録。'}
  default.update(notes)
  self.d['researchCompleteness']={'version':2,'domains':[{'domain':dom,'status':'NOT_APPLICABLE' if dom in na else 'CHECKED','sourceIds':['analysis'],'note':default[dom]} for dom in DOMAINS],'machineSpecificQueries':QUERIES[self.index],'candidateLedger':self.ledger}
  assert all(s['claims'] for s in self.d['sources'])
  target=BASE/'research-drafts'/self.wave/(self.mid+'.json');target.parent.mkdir(parents=True,exist_ok=True);target.write_text(json.dumps(self.d,ensure_ascii=False,indent=2)+'\n');print(self.mid,len(self.d['findings']),len(self.d['blockedItems']))
def tiers(pairs):return [(a,'設定6' if i==6 else f'設定{i}以上',X) for a,i in pairs]
def counts(nums):return tiers([(str(i)*3+'枚',i) for i in nums])

r=Research(0,'スマスロ 回胴黙示録カイジ 狂宴','https://1geki.jp/slot/l_kaiji_ky/0/','カイジ狂宴 設定判別・抽選・示唆')
r.source('official','https://www.sammy.co.jp/japanese/product/pachislot/kai_ky/','カイジ狂宴 サミー公式','official');r.fact('identity','2024年カイジ狂宴の機種同定','パチンコ・過去作を対象にしない。',['official'])
r.rates('bonus-initial','ボーナス初当たり',[384.9,376,360,324.6,304.2,290.6],'通常ゲーム数に対するボーナス初当たり回数。ST中の当たり・引き戻しは含めません。')
r.rates('bonus-total','ボーナス合算',[180.4,175.9,167.8,154.2,145.7,139.3],'全遊技ゲーム数に対するボーナス回数。連続当たりを含む合算で、初当たりとは分けます。',trial='TOTAL_GAME_TRIAL')
r.rates('cz','運否天賦チャンス',[243.3,237.6,225.7,199.4,185.1,176.8],'通常ゲーム数に対する運否天賦チャンス突入回数。')
r.num('cz-success','運否天賦チャンス成功',[.623,.627,.63,.636,.641,.646],'運否天賦チャンスを最後まで確認した回数と、その成功回数。',trial='KAIJI_CZ_COMPLETED_TRIAL',conditional=True)
for id,label,vs in [('watermelon','スイカ',[79.9,79,78,77.1,75.3,72.8]),('weak-cherry','弱チェリー',[218.5,211.4,204.8,198.6,187.2,182]),('weak-chance','弱チャンス目',[84,81.9,79.9,79,78,77.1]),('strong-cherry','強チェリー',[528.5,512,496.5,481.9,468.1,455.1])]:r.rates(id,label,vs,'全遊技ゲーム数に対する'+label+'成立回数。停止形を確認して他の役を混ぜません。',trial='TOTAL_GAME_TRIAL')
r.category('first-bar','赤7ボーナスの初回BAR報酬',['運否天賦','トネガワ','ハンチョウ'],[[96.9,2.7,.4],[95.3,4.3,.4],[94.9,4.7,.4],[92.2,7.4,.4],[90.6,9,.4],[90.2,9.4,.4]],'KAIJI_RED7_FIRST_BAR_TRIAL','赤7ボーナスの初回BAR揃いだけを数えます。青7とエピソードレベル5は除きます。')
r.dependent(['cz','bonus-initial','bonus-total','cz-success','first-bar'],'kaiji-bonus-path','CZ成功が初当たりにつながり、初当たり後の報酬と連続当たりがボーナス合算を作る上流・下流の関係です。同時加算を避け、CZ、初当たり、合算、成功、報酬の順で未観測時のみ代用します。')
r.block('zawa','弱レア役からざわ高確','高確移行率の設定別数値はありますが、移行・終了する内部高確を演出だけで全件確定できません。',raw=dict(zip(map(str,range(1,7)),[.25,.25,.266,.289,.301,.309])))
r.block('direct','閃き前兆からトネガワRUSH直撃','設定1・6の数値のみで、設定2～5の確率は未公表です。',raw={'1':.004,'6':.012})
r.block('chain-mode','連続当たり終了時の内部モード','終了後の内部モードを初当たりゲーム数だけで確定できず、公表表の全残余カテゴリも未確定です。')
r.evidence('end','ボーナス終了画面',[('カイジ①','基本パターン',D),('カイジと犬','偶数設定示唆',P),('カイジ②','高設定示唆',P),('敵キャラ集合','設定2以上',X),('トネガワ','設定2・3否定',X),('ハンチョウ地下','設定2・3・4否定',X),('美心','設定4以上',X),('札束風呂','設定6',X)],details=['トネガワ・ハンチョウには高設定示唆もありますが、出現率は不明です。確定した否定条件だけを適用します。'])
r.evidence('win','獲得枚数表示',tiers([('456OVER',4),('666OVER',6)]))
r.evidence('ending-voice','エンディングのレア役PUSH',[('救えぬ偽善者','奇数設定示唆',P),('甘えを捨てろ','偶数設定示唆',P),('魔力','高設定示唆',P),('456賽への言及','設定4以上',X),('帝愛は愛されねばならん','設定6',X)])
r.evidence('st-screen','ST再セット時の画面',[('トネガワ①・②','基本パターン',D),('トネガワ③','高設定示唆',P),('ハンチョウ①・②','基本パターン',D),('ハンチョウ③','高設定示唆',P)])
r.evidence('trophy','サミートロフィー',tiers([('銅',2),('銀',3),('金',4),('キリン',5),('虹',6)]),details=['ボーナス終了時に確認します。沼ボーナスとエンディングボーナス終了時は対象外です。'])
r.source('trophy-rate','https://1geki.jp/slot/l_kaiji_ky/5/','カイジ サミートロフィー出現率・カスタム条件')
r.block('trophy-rate','区間別のトロフィー出現率','カスタムなしの各1000G区間の出現率は公表されていますが、カスタム有無を遊技者が確定できません。色の設定条件はカスタムによって変わらないため保持します。',['trophy-rate'],raw={'0-1000':[[0,0,0,0,0],[1.30,0,0,0,0],[.30,1.20,0,0,0],[1.20,.23,.12,0,0],[1.16,.24,.12,.08,0],[1.16,.25,.12,.08,.04]],'1001-2000':[[0,0,0,0,0],[1.30,0,0,0,0],[.30,1.20,0,0,0],[1.32,.15,.08,0,0],[1.32,.16,.08,.04,0],[1.34,.17,.08,.04,.02]],'2001-3000':[[0,0,0,0,0],[.19,0,0,0,0],[.05,.26,0,0,0],[.26,.05,.03,0,0],[.31,.07,.03,.02,0],[.37,.08,.04,.03,.01]],'3001-4000':[[0,0,0,0,0],[.19,0,0,0,0],[.05,.26,0,0,0],[.11,.11,.11,0,0],[.11,.11,.11,.11,0],[.10,.10,.10,.10,.10]],'4001-5000':[[0,0,0,0,0],[.19,0,0,0,0],[.05,.26,0,0,0],[.11,.11,.11,0,0],[.11,.11,.11,.11,0],[.10,.10,.10,.10,.10]],'5001-6000':[[0,0,0,0,0],[.19,0,0,0,0],[.05,.26,0,0,0],[.07,.10,.17,0,0],[.04,.07,.11,.22,0],[.03,.05,.08,.10,.26]],'6001-7000':[[0,0,0,0,0],[.19,0,0,0,0],[.05,.26,0,0,0],[.36,.54,.90,0,0],[.24,.36,.59,1.19,0],[.15,.29,.44,.59,1.46]],'7001-8000':[[0,0,0,0,0],[.19,0,0,0,0],[.05,.26,0,0,0],[.23,.23,1.36,0,0],[.12,.12,.36,1.78,0],[.11,.11,.22,.29,2.19]],'8001+':[[0,0,0,0,0],[.63,0,0,0,0],[.19,.48,0,0,0],[.58,.07,.04,0,0],[.59,.07,.04,.02,0],[.60,.07,.04,.02,.01]],'unit':'percent per eligible bonus end','columns':['bronze','silver','gold','kirin','rainbow']})
r.fact('common','強チャンス目の確率・天井の基本仕様','公開されている全設定共通値を設定差として加算しない。')
r.done({'MACHINE_SPECIFIC':'赤7初回BARと青7・レベル5を分離。ざわ高確の見た目を内部状態と同一視しない。','EVIDENCE':'トネガワ・ハンチョウの設定否定と高設定示唆を混ぜない。'})

r=Research(1,'Lラブ嬢3 ～Wご指名はいかがですか？～','https://nana-press.com/kaiseki/machine/651/18111/','ラブ嬢3 設定判別・抽選・示唆')
r.rates('at','AT初当たり',[285.2,278,263.4,242.7,224.9,210.4],'通常ゲーム数に対するAT初当たり回数。継続・引き戻しは除きます。')
r.rates('cz','ラブゾーン',[181.7,175.9,161.2,147.1,134.1,124.5],'通常ゲーム数に対するラブゾーン突入回数。')
r.rates('upper','Wご指名RUSH',[1831.1,1806.8,1719.7,1596.1,1471.7,1369.2],'全遊技ゲーム数に対するWご指名RUSH突入回数。AT中の経路を含みます。',trial='TOTAL_GAME_TRIAL')
r.num('cz-failure-at','ラブゾーン失敗後のAT当選',[.004,.004,.004,.008,.012,.016],'ラブゾーン失敗時だけのAT本前兆抽選です。直後に別の小役で当選したATを区別できません。',trial='LOVEJOU_CZ_FAILURE_TRIAL',conditional=True,status='UNRESOLVED')
r.category('relax','リラクの泉の突入抽選',['非当選','フェイク','本前兆'],[[97.3,.8,2],[97.3,.8,2],[96.5,1.2,2.3],[95.7,1.6,2.7],[95.7,1.6,2.7],[95.7,1.6,2.7]],'LOVEJOU_AT_END_TRIAL','AT終了時の内部抽選結果です。フェイクと本前兆を途中の別抽選から全件区別できません。',status='UNRESOLVED')
r.category('cz-level','ラブゾーン開始レベル',['お店前','Club Luxe','ALL CAST','コスプレ','Wご指名チャンス'],[[62.5,25,10.9,1.2,.4],[62.1,25.4,10.9,1.2,.4],[61.7,25.8,10.9,1.2,.4],[61.3,26.2,10.9,1.2,.4],[60.9,26.6,10.9,1.2,.4],[60.5,27,10.9,1.2,.4]],'LOVEJOU_CZ_START_TRIAL','ラブゾーン突入時の初期レベルです。消化中の昇格後のステージは数えません。')
r.dependent(['cz','at','upper','cz-level'],'lovejou-at-path','ラブゾーンがATの入口になり、ATから上位RUSHにつながります。開始レベルもCZ成功へ影響するため同時加算せず、CZ、AT、上位、開始レベルの順に代用します。')
r.evidence('stamp','AT終了画面のスタンプ',tiers([('可：ボーイ',2),('吉：天木じゅん',3),('良：ドレス',4),('優：水着',5),('極：金色の水着',6)]))
r.evidence('count','獲得枚数表示',counts([2,3,4,5,6]))
r.block('end-no-stamp','スタンプなしの終了画面','公開表で示唆内容が調査中の画面があるため、画面の人数だけで奇数・偶数の確定条件を作りません。')
r.block('relax-mode','リラクの泉・失敗後の内部状態','内部モードの振り分けは公開されていますが、抽選時の内部状態と選択結果を全件確定できません。')
r.fact('allcast','ALL CAST達成','通常ATからの達成経路を含む出現値で、AT初当たりと独立した情報として重ねない。')
r.done({'POST_EVENT_TRANSITION':'失敗直後のATとリラク突入時の本前兆を、追加抽選結果から区別できず保留。','BONUS_TYPE_CONDITIONAL':'Wご指名は通常ATを経る上位経路。','MACHINE_SPECIFIC':'初期CZレベルと消化中の昇格を混ぜない。'})

r=Research(2,'Lゴブリンスレイヤー','https://nana-press.com/kaiseki/machine/533/14521/','2023年ゴブリンスレイヤー 設定判別')
r.source('draw','https://1geki.jp/slot/s_l_goblinslayer/41/','通常抽選・スイカカウンター・リプレイ3連')
r.source('official','https://www.fujimarukun.co.jp/products/l_goblin/','藤商事 ゴブリンスレイヤー公式','official');r.fact('identity','2023年初代ゴブリンスレイヤー','後継機やパチンコを混ぜない。',['official'])
r.rates('at','AT初当たり',[547.9,538.4,517.7,492.3,470.5,435.7],'通常ゲーム数に対するゴブリンスレイヤーRUSH初当たり回数。')
r.rates('cz','CZ合算',[226,223,215,204,196,184],'通常ゲーム数に対する3種類すべてのCZ突入回数。')
for id,label,vs in [('mission','ミッション',[327,323,309,293,281,261]),('chance','チャンス',[833,823,804,777,757,723]),('battle','バトル',[6000,5588,5216,4823,4491,4083])]:r.rates('cz-'+id,'CZ：'+label,vs,'通常ゲーム数に対するゴブリンスレイヤー'+label+'突入回数。CZ合算の一部です。')
r.rates('common-bell','共通ベル',[102.5,97.5,93.1,86.2,81.9,71.9],'通常ゲーム数に対する共通ベル成立回数。押し順ベルと区別できる停止形を確認します。')
r.num('replay3','リプレイ3連からCZ',[.031,.043,.066,.109,.148,.172],'通常時にリプレイが3連続した3回目の抽選と、そこからのCZ当選を数えます。4連目の確定抽選や別のレア役でのCZを混ぜません。',trial='GOBLIN_REPLAY3_TRIAL',conditional=True,sids=['draw'])
for id,label,vs in [('g300','300GでCZ当選',[.203,.207,.215,.227,.238,.246]),('g500','500GでCZ当選',[.203,.207,.227,.254,.297,.387])]:r.num(id,label,vs,'通常時に対象ゲーム数へ到達した回数と、そのゲーム数契機のCZ当選回数。レア役での当選を区別できない場合は記録しません。',trial='GOBLIN_'+id.upper()+'_TRIAL',conditional=True,sids=['draw'])
for id,label,vs in [('water3-reset','スイカ3回：変更・AT後のCZ当選',[.666,.668,.673,.678,.682,.708]),('water3-cz','スイカ3回：CZ後のCZ当選',[.438,.44,.458,.458,.464,.508]),('water-multiple','スイカ6・9回以降のCZ当選',[.25,.254,.266,.277,.285,.344])]:r.num(id,label,vs,'表示カウンターと直前の終了条件を確認し、対象回数に到達した回数とそのカウンター契機のCZ当選を数えます。別契機と区別できない場合は記録しません。',trial='GOBLIN_'+id.upper().replace('-','_')+'_TRIAL',conditional=True,sids=['draw'])
r.category('replay-cz-type','リプ・ベル連からのCZ種別',['ミッション','チャンス','バトル'],[[76.2,22.3,1.6],[75.8,22.3,2],[75.4,22.3,2.3],[75,22.3,2.7],[74.6,22.3,3.1],[74.2,22.3,3.5]],'GOBLIN_CHAIN_CZ_TRIAL','リプレイ連・ベル連が契機と確定したCZだけを、突入時の種類で分類します。',sids=['draw'])
r.dependent(['cz','at','cz-mission','cz-chance','cz-battle','replay3','g300','g500','water3-reset','water3-cz','water-multiple','replay-cz-type'],'goblin-cz-at-path','個別CZと各契機の抽選がCZ合算を構成し、CZ成功からATへつながります。合算、AT、個別CZ、条件別抽選の順で代用し、同じ経路を二重に数えません。')
r.block('strong-cherry','通常状態・履歴1個目の強チェリー','全設定のCZ振り分けは公表されていますが、成立時の内部通常状態をステージの示唆だけで確定できません。',['draw'],raw={'mission':[.188,.195,.219,.242,.254,.258],'chance':[.086,.09,.094,.102,.105,.109],'battle':.023,'at':.004})
r.block('ceiling','600G・1000G・1500G天井の振り分け','設定別の天井振り分けは未公表です。早い通常当選から選択された天井を確定することもできません。')
r.evidence('end','AT終了画面',[('ゴブリンスレイヤーのみ','基本パターン。設定変更示唆',D),('女神官','偶数設定示唆',P),('妖精弓手','高設定示唆（弱）',P),('受付嬢','高設定示唆（強）',P)]+tiers([('剣の乙女',2),('牛飼娘',4),('全員①',4),('全員②',6)]))
r.evidence('coin','AT終了時のコイン',tiers([('銅',2),('銀',3),('金',4),('デンジャー柄',5),('虹',6)]))
r.evidence('feather','CZ失敗・AT終了時の羽',[('白','基本パターン',D),('黒','高設定示唆',P),('黒が大量','設定2以上',X),('羽なし','設定5以上',X)],details=['終了時の演出全体を確認した場合だけ記録します。演出の見逃しを羽なしとは数えません。'])
r.evidence('count','獲得枚数表示',[('246枚','設定2・4・6',X),('356枚','設定3・5・6',X),('456枚','設定4以上',X),('52枚','設定5以上',X),('666枚','設定6',X)])
r.fact('bell2','ベル2連でのCZ抽選','50%で全設定共通。4連リプレイのCZ確定も設定差として使わない。',['draw'])
r.done({'SMALL_ROLE':'共通ベルの停止形と通常時の成立を対象にする。','ROLE_CONDITIONAL_DISTRIBUTION':'強チェリー履歴1個目でも内部通常状態が未確定なら保留。','CARRY_OVER':'カウンターはその契機のCZ当選で0へ戻る。表示を継続して追跡する。','MACHINE_SPECIFIC':'リプレイ3連と4連を分離し、3連以上という省略表現をそのまま対象条件にしない。'})

r=Research(3,'Lゴジラ','https://nana-press.com/kaiseki/machine/919/28861/','Lゴジラ 設定判別')
r.source('cross','https://1geki.jp/slot/l_godzilla/0/','Lゴジラ 設定判別・CZ振り分け')
r.rates('at','AT初当たり',[680.9,662.6,611,511.3,447.1,420.4],'通常ゲーム数に対するゴジラバトル初当たり回数。継続バトルは除きます。',sids=['analysis','cross'])
r.rates('cz','CZ初当たり',[306.9,304,303,302.1,299.6,295.5],'通常ゲーム数に対するCZ突入回数。')
r.category('opponent','CZの対戦相手',['ラドン','ガイガン','ビオランテ','デストロイア','キングギドラ'],[[41.4,36.6,16.8,5,.1],[39.6,37,17.9,5.4,.1],[38,37.2,18.7,5.9,.1],[35.8,36.4,20.9,6.7,.1],[33.9,35.1,23.3,7.5,.1],[32.2,34.5,25.1,8.1,.1]],'GODZILLA_CZ_ENTRY_TRIAL','CZ突入時に決まった対戦相手を1回ずつ記録します。',sids=['cross'])
r.dependent(['at','opponent','cz'],'godzilla-at-path','CZの相手で成功期待度が変わり、CZ成功がATへつながる経路です。AT、相手、CZの順に未観測時だけ代用します。')
r.block('search','探索ZONE出現','設定1・6の出現値のみで、設定2～5の値は未公表です。',raw={'1':'1/91.3','6':'1/72.5'})
r.block('replay-point','リプレイから粉砕ポイント','設定1の獲得率だけで、設定2～6の数値は未公表です。',raw={'1':.152})
r.evidence('menu','メニュー画面',[('ヘリコプター','偶数設定示唆',P),('戦車','高設定示唆（弱）',P),('メーサー殺獣光線車','高設定示唆（強）',P)]+tiers([('轟天号',2),('スーパーXIII',4),('3式機龍',6)]))
r.evidence('end','ゴジラボーナス終了画面',[('ヘドラ・アンギラス','基本パターン',D),('ラドン','奇数設定示唆',P),('ガイガン','偶数設定示唆',P),('ビオランテ','奇数設定・高設定示唆',P),('デストロイア','偶数設定・高設定示唆',P)]+tiers([('キングギドラ',4),('赤いゴジラ',5),('白黒ゴジラ',6)]))
r.evidence('trophy','AT終了時のトロフィー',tiers([('銅',2),('銀',3),('金',4),('虎柄',5),('虹',6)]))
r.evidence('movie','EX終了ムービー',[('①','基本パターン',D),('②','高設定示唆（弱）',P),('③','高設定示唆（中）',P),('④','高設定示唆（強）',P),('⑤','設定5以上',X)])
r.evidence('operator','通常時のオペレーター',[(a,b,t) for a,b,t in [('ゴジラの怒りを秘める','高設定示唆',P),('ゴジラの力強さ','高設定示唆',P),('巨大な力が眠る','高設定示唆',P)]]+tiers([('怪獣の世界に足を踏み入れる',2),('最後の一匹とは思えない',2),('怪獣の力が宿る',3),('巨大な怪獣の目覚め',3),('怒りの象徴',4),('心の闇を映す鏡',4),('地球の守護者',5),('未来を守るために戦う',5),('伝説が息づく',6),('伝説が刻まれる',6)]),sids=['cross'],details=['通常時のオペレーターが話したセリフの内容で分類します。通常のゴジラ目撃情報は設定示唆ではありません。'])
r.done({'MACHINE_SPECIFIC':'CZ相手の全5種類を保持し、丸め誤差以外の数値を補わない。','EVIDENCE':'メニュー・AT終了・トロフィー・EXムービーの確定条件を保持。'})

r=Research(4,'Lうしおととら 白面決戦','https://nana-press.com/kaiseki/machine/918/28683/','白面決戦 設定判別')
r.source('draw','https://nana-press.com/kaiseki/machine/918/28689/','白面決戦 通常時の内部状態とCZ抽選')
r.source('cross','https://www.p-world.co.jp/machine/database/10236','白面決戦 機種情報・小役・初当たり')
r.rates('cz','CZ初当たり',[178,175.6,169.7,164.5,161.9,159],'通常ゲーム数に対するうしとらチャンス初当たり回数。',sids=['analysis','cross'])
r.rates('at','AT初当たり',[397.3,389.6,378,365.6,360,356.1],'通常ゲーム数に対するうしとらBONUS初当たり回数。ST中の当たりは除きます。')
r.dependent(['at','cz'],'ushio-cz-at-path','CZ成功からATへ進む経路を含みます。ATを優先し、未観測の場合だけCZを使用します。')
r.block('reset-ceiling','設定変更後のAT間天井','設定別の2000・2250・2500G振り分けは公開されていますが、先にATへ当選した場合の選択天井を確定できません。',raw={'2000':[15.5,23.25,27.91,46.51,55.81,56.59],'2250':[.39]*6,'2500':[84.11,76.35,71.70,53.10,43.8,43.02]})
r.block('role-cz','内部状態別・成立役別のCZ抽選','状態別の設定1の値は公開されていますが、全設定の率が揃わず、内部状態の示唆ステージも確定条件にはできません。',['draw'])
r.block('ushitora-mode','うしとらモード移行','CZ失敗回数やリセットでの内部モード移行は、その後のCZ種別だけから全件確定できません。')
r.evidence('trophy','ダイナマイトトロフィー',tiers([('銅',2),('銀',3),('金',4),('てんとう虫柄',5),('虹',6)]))
r.evidence('count','獲得枚数表示',counts([2,3,4,5,6])+[('246枚','設定2・4・6',X),('456枚','設定4以上',X)])
r.fact('roles','通常リプレイ・各チェリー・スイカ・チャンス目・妖目','公開小役確率は全設定共通。',['cross'])
r.done({'THRESHOLD_BEHAVIOR':'リセット天井の数値は保持するが、早い当選による未観測の選択天井を補わない。','SMALL_ROLE':'P-WORLDで全設定共通小役を照合。','MACHINE_SPECIFIC':'通常AT初当たりとSTループのうしとらBONUSを分ける。'})

r=Research(5,'スマート沖スロ アメイジングライブ','https://1geki.jp/slot/l_amazinglive/0/','アメイジングライブ 設定判別',settings=(1,2,4,5,6))
r.source('spec','https://nana-press.com/kaiseki/machine/928/27292/','アメイジングライブ スペック・設定L')
r.source('roles','https://1geki.jp/slot/l_amazinglive/4/','アメイジングライブ 小役確率')
r.source('official','https://www.slot-pioneer.co.jp/product/amazinglive/','アメイジングライブ パイオニア公式','official');r.fact('identity','パイオニアの2025年スマート沖スロ','他社の沖スロの設定示唆を流用しない。',['official'])
r.rates('initial','ボーナス初当たり',[274,259.6,229.3,206.9,189.9],'連チャン区間を除く初当たり対象ゲーム数と、通常区間でのボーナス初当たり回数。33G以内の継続当たりやBIG1G連は含めません。',trial='NON_CHAIN_BONUS_INITIAL_GAME_TRIAL',sids=['analysis','spec'])
r.rates('big-total','BIG合算',[213,202.5,181.6,165.7,153.4],'全遊技ゲーム数に対するBIG回数。継続当たりを含みます。',trial='TOTAL_GAME_TRIAL',sids=['spec'])
r.rates('reg-total','REG合算',[370,349.5,310.2,280.7,258],'全遊技ゲーム数に対するREG回数。継続当たりを含みます。',trial='TOTAL_GAME_TRIAL',sids=['spec'])
r.dependent(['initial','big-total','reg-total'],'amazing-bonus-path','通常初当たりが33G以内の連続当たりや1G連を生み、BIG・REG合算へ影響します。初当たり、BIG、REGの順で代用し、同時に加算しません。')
r.block('mode','AC・CEX・天国モードの選択と継続','モードやACによる連チャンの仕様は公開されていますが、全設定の移行率・継続率は未公表です。')
r.block('cycle','ゾロ目ゲーム数・レア役規定回数','設定差を持つ全設定の規定回数・当選率は未公表です。')
r.fact('common-roles','スイカ・チェリー・リーチ目・中段チェリー','公開値は全設定共通。',['roles'])
r.fact('settingL','設定L・1・2・4・5・6の6段階','数値判別は公表された1・2・4・5・6の5設定を対象とし、存在しない設定3を補わない。設定Lは独立した識別仕様。',['spec'])
r.done({'CZ':'独立したCZ抽選はなく、ACはボーナス後の連チャン系統。','AT':'独立した通常AT入口の数値はなく、疑似ボーナスで構成。','EVIDENCE':'本機の設定番号を確定する色別ランプ・トロフィー等は調査資料で確認できない。過去の沖スロから作らない。','MACHINE_SPECIFIC':'設定3なし。33G以内と1G連を初当たりに混ぜない。'},na=['CZ'])

r=Research(6,'吉宗','https://nana-press.com/kaiseki/machine/920/29003/','2025年吉宗 設定判別')
r.source('draw','https://nana-press.com/kaiseki/machine/920/29010/','吉宗 2026年9月更新のリーチ目・純ハズレ抽選')
r.source('mode','https://nana-press.com/kaiseki/machine/920/29011/','吉宗 モード移行抽選')
r.rates('bonus','ボーナス初当たり',[378.9,369.6,358.8,335.1,318.5,292.4],'通常ゲーム数に対するボーナス初当たり回数。1G連のボーナスは含めません。')
r.rates('common-bale','共通俵',[819.2,744.7,682.7,585.1,512,455.1],'通常ゲーム数に対する順押しの右下がり俵揃い12枚の回数。ナビのある押し順俵を混ぜません。')
r.rates('reach','通常時のリーチ目',[33288.1,24966.1,12483,6241.5,4161,3120.8],'高確率・鷹狩り・連続演出中を除く通常ゲーム数と、対象区間のリーチ目成立回数。対象外のゲーム数・成立を数えません。',trial='YOSHIMUNE_NON_PREMONITION_GAME_TRIAL',sids=['draw'])
r.dependent(['bonus','reach'],'yoshimune-bonus-path','リーチ目はボーナス解除経路の一部です。ボーナス初当たりを優先し、未観測時だけ対象区間のリーチ目を使用します。')
r.block('pure-miss','純ハズレからの解除とフェイク高確率','設定別の内部抽選値は公開されていますが、解除を規定ゲーム数・他の役の経路と全件区別できません。',['draw'])
r.block('mode','リセット・ボーナス後のモード移行','移行表は公表されていますが、移行元・移行先の内部モードは早い当選だけから確定できません。',['mode'])
r.evidence('card','BIG終了後の花札',[('黒：青短','高設定示唆（弱）',P),('黒：赤短','高設定示唆（強）',P)]+tiers([('銅：柳・ちび姫',2),('銀：松・爺',3),('金：芒・吉宗',4),('ピンク：桜・姫',5),('虹：桐・鷹',6)]))
r.fact('voice','終了ボイス・鷹狩りや1G連示唆','次の状態・継続の示唆を設定確定表示へ変換しない。')
r.done({'CZ':'高確率・鷹狩りは解除の演出で、独立したCZ初当たりとして数えない。','AT':'疑似ボーナス・1G連を中心とする機種。','MACHINE_SPECIFIC':'2026年9月の追加解析を確認。リーチ目の対象外状態を明示。','SMALL_ROLE':'共通俵の順押し停止形と押し順俵を区別。'})

r=Research(7,'L麻雀物語','https://nana-press.com/kaiseki/machine/931/29160/','2025年麻雀物語 設定判別')
r.source('cross','https://1geki.jp/slot/l_mjnmngtr/0/','麻雀物語 初当たり・通常直撃')
r.source('add','https://hisshobon.com/machineinfo/86576/','麻雀物語 特定上乗せ表示と後乗せ除外')
r.rates('at','AT初当たり',[615.2,600.3,580.5,545.5,537.9,531.4],'通常ゲーム数に対する麻雀闘牌の初当たり回数。継続セットは含めません。',sids=['analysis','cross'])
r.rates('bonus','ボーナス初当たり',[433.3,431.8,426.6,420.2,417.9,416.5],'通常ゲーム数に対する麻雀ボーナス初当たり回数。AT中の当たりを含めません。')
r.rates('initial-total','ボーナス・AT初当たり合算',[354.1,349.2,342.1,328.8,326,323.8],'通常ゲーム数に対するボーナス・AT初当たりの合計回数。ボーナスからATへ進んだものを初当たり2回として数えません。')
r.rates('direct','AT直撃（前兆昇格込み）',[7945.6,6529.1,5649.1,4012.7,3859.1,3707.4],'通常ゲーム数に対するボーナスを挟まずATに入った回数。前兆中の昇格を含む公開値を使用します。')
r.rates('kotei','AT中の煌帝出現',[891.5,887,868.7,808.1,754.6,747.9],'AT中のゲーム数に対する煌帝出現回数。終了時などの強制出現は含めません。',trial='MAHJONG_AT_ELIGIBLE_GAME_TRIAL')
r.dependent(['at','initial-total','direct','bonus'],'mahjong-initial-path','ボーナスからATへの経路と、AT直撃・初当たり合算には包含・上流下流の関係があります。AT、合算、直撃、ボーナスの順に代用して二重加算を避けます。')
r.block('pure-direct','前兆昇格を除いたAT直撃','本前兆中の昇格と純粋な通常直撃を実戦で全件区別することが難しいため、昇格込みの公開値と分けます。')
r.block('cz-success','CZ撃破数別のボーナス当選','500～699体・700～999体の数値は設定1のみです。',raw={'1':{'500-699':.215,'700-999':.41}})
r.block('mashi','通常マシロックの7揃い','通常時の設定1の値だけで、全設定の率が未公表です。',raw={'1':'1/127.1'})
r.block('kotei-win','煌帝に勝利','設定1の勝利期待度のみで、設定2～6の値は未公表です。',raw={'1':.84})
r.block('count','獲得枚数のゾロ目表示','資料では従来機種からの予想と明記されています。本機で未確認の設定確定条件を作りません。')
r.block('nagi','隠れ凪のセリフ','示唆の対応は他の平和機種を参考とした推測で、本機の設定確定条件として未確認です。')
r.evidence('stamp','終了画面スタンプ',tiers([('可',2),('良',4),('優',5),('極',6)]))
r.evidence('screen','ボーナス・AT終了画面',[('ボーナス：さやか','基本パターン',D),('ボーナス：あやか','奇数設定示唆',P),('ボーナス：まどか','偶数設定示唆',P),('AT：三姉妹','基本パターン',D),('AT：さやか','高設定示唆（弱）',P),('AT：師匠','高設定示唆（強）',P)])
r.evidence('add','AT中の直乗せ表示',tiers([('+44G',4),('+55G',5),('+66G',6)]),sids=['analysis','add'],details=['レア小役からの直乗せ表示だけを記録します。後乗せで同じゲーム数が表示されても設定示唆にはなりません。'])
r.evidence('push','ラストジャッジのハルルナPUSH',[('ハルルナPUSH','設定4以上',X)])
r.evidence('voice','終了時PUSHボイス',[('さやか','高設定示唆（弱）',P),('マシロ','高設定示唆（強）',P)],details=['ボーナスのAT非当選時・AT終了時にPUSHで確認します。パトランランの声は次のチャンス示唆です。'])
r.done({'SUCCESS_RATE':'煌帝の84%とCZの撃破数別数値は設定1のみで保留。','MACHINE_SPECIFIC':'純直撃と前兆込み直撃を分離。後乗せの44・55・66Gは確定条件にしない。','EVIDENCE':'獲得枚数と隠れ凪の他機種参考情報は確定条件へ流用しない。'})

r=Research(8,'アイドルマスター ミリオンライブ！ネクストプロローグ','https://nana-press.com/kaiseki/machine/921/29067/','ミリオンライブ ネクストプロローグ 設定判別')
r.source('cross','https://www.p-world.co.jp/machine/database/10216','ミリオンライブ ネクストプロローグ 型式・確率')
r.source('official','https://www.yamasa-next.co.jp/slp/model/01/','山佐 開発情報・レア役確率記載削除','official')
r.rates('cz','CZ初当たり',[428,415.5,378.4,353.8,322.7,306.2],'通常ゲーム数に対するSEVEN CHANCE初当たり回数。',sids=['analysis','cross'])
r.rates('bonus','ボーナス初当たり',[347,337.4,314,280.6,256.8,242],'通常ゲーム数に対するボーナス初当たり回数。継続当たりは含めません。',sids=['analysis','cross'])
r.dependent(['bonus','cz'],'idol-cz-bonus-path','CZ成功がボーナスの入口になる経路があります。ボーナスを優先し、未観測時のみCZで代用します。')
r.block('space','宇宙直撃高確への移行・滞在','高設定ほど入りやすい情報はありますが、全設定の移行率・滞在率は未公表で、見た目のステージと内部状態も同一とは限りません。')
r.block('zone','天国・300Gでの当選','設定差の傾向のみで全設定の当選率が未公表です。')
r.block('roles','レア役確率','メーカーは正確な記載が困難としてレア役確率の記載を削除しています。状態により変わる値を通常一定の確率として補いません。',['official'])
r.block('trophy','ケロットトロフィーの各色','本機の資料では過去の山佐機種を参考とした示唆です。本機で確定した各色の設定条件が未確認です。')
r.evidence('end','ボーナス終了画面',[('SDバレンタイン','奇数設定示唆（弱）',P),('バレンタイン','奇数設定示唆（強）',P),('SDホワイトデー','偶数設定示唆（弱）',P),('ホワイトデー','偶数設定示唆（強）',P)]+tiers([('赤枠',2),('紫枠',2),('銀枠',3),('金枠：指4本',4),('金枠：ケーキ5個',5),('虹枠',6)]),details=['紫枠には高設定示唆もありますが、確率は不明です。確定している設定2以上だけを適用します。'])
r.fact('reset','リセット時のチャンス・天国振り分け','公開されたチャンス75.8%・天国24.2%を設定別差として使用しない。')
r.done({'SMALL_ROLE':'メーカーの記載削除を確認し、状態別の未確定確率を補間しない。','MACHINE_SPECIFIC':'前作と区別。宇宙直撃高確を表示ステージだけで確定しない。','EVIDENCE':'過去機種参考のトロフィーと、本機確認済みの終了画面を分ける。'})

r=Research(9,'ようこそ実力至上主義の教室へ','https://nana-press.com/kaiseki/machine/935/29484/','よう実 設定判別')
r.rates('cz','CZ初当たり',[148.6,143.8,138,130.3,121.8,115.5],'通常ゲーム数に対するCZ初当たり回数。')
r.rates('at','AT初当たり',[329.9,317.9,302.8,281.5,260,243.3],'通常ゲーム数に対するAT初当たり回数。継続セットは含めません。')
r.num('upper-cz','CZの実力至上主義試験選択',[.103,.122,.14,.152,.163,.173],'AT終了後のCZのうち、周期1・4回目とポイント契機を除いた突入回数と、実力至上主義試験が選ばれた回数。',trial='YOUJITSU_POST_AT_CZ_ELIGIBLE_TRIAL',conditional=True)
r.num('flash','CZ成功時のDAXELフラッシュ',[.005,.006,.01,.015,.02,.025],'CZ成功回数と、成功時にDAXELフラッシュが発生した回数。失敗時やAT中のフラッシュは含めません。',trial='YOUJITSU_CZ_SUCCESS_TRIAL',conditional=True)
r.num('red-button','連続演出の赤ボタン',[.01,.012,.014,.015,.017,.019],'対象の連続演出の終了ボタンを確認した回数と、赤ボタンだった回数。CZ・AT中などの別演出は含めません。',trial='YOUJITSU_CONTINUOUS_EFFECT_TRIAL',conditional=True)
r.dependent(['at','cz','upper-cz'],'youjitsu-cz-at-path','CZの上位種別で成功期待度が変わり、CZ成功からATへつながります。AT、CZ、上位種別の順に代用します。')
r.block('role-cz','内部CZモード別の小役抽選','内部モード別の設定値はありますが、成立時の内部モードを表示ステージだけで全件確定できません。',raw={'watermelon':[.016,.02,.027,.039,.047,.055],'weakChance':[.031,.035,.043,.066,.102,.125],'weakCherry':[.063,.07,.086,.113,.152,.188]})
r.evidence('count','獲得枚数表示',[('246枚','設定2・4・6',X),('456枚','設定4以上',X),('666枚','設定6',X)])
r.evidence('pair','ボーナスのキャラ紹介順',[('綾小路→堀北鈴音','設定1否定',X),('綾小路→櫛田','設定2否定',X),('綾小路→佐倉','設定3否定',X),('綾小路→軽井沢','設定4否定',X),('堀北鈴音→堀北学','設定4以上',X),('綾小路→龍園','設定6',X)],details=['1回のボーナス内で紹介された2人の順番を確認します。別のボーナスの紹介を組み合わせません。'])
r.evidence('single','ボーナスのキャラ紹介',[('一之瀬・神崎','奇数設定示唆',P),('坂柳・堀北学・橘','偶数設定示唆',P),('茶柱','高設定示唆',P)],details=['堀北鈴音→堀北学の順番は別欄の設定4以上条件です。単独キャラの示唆と重複して加算しません。'])
r.evidence('at-end','AT終了画面',[('軽井沢','偶数設定示唆',P),('一之瀬','高設定示唆（弱）',P),('坂柳','高設定示唆（強）',P)]+tiers([('堀北・特殊画面',2),('坂柳・特殊画面',4),('龍園・特殊画面',5),('龍園VS綾小路',6)]))
r.evidence('bonus-end','ボーナス終了画面',[('櫛田','高設定示唆',P)])
r.block('ending-voice','エンディングの目押しボイス','白7・赤7の目押し後のボイスはありますが、各ボイスの本機の設定条件は未公表です。')
r.done({'MACHINE_SPECIFIC':'AT後CZの周期1・4回目とポイント契機を除外し、紹介2人を同一ボーナス内の順番で扱う。','EVIDENCE':'否定条件を高設定示唆に置き換えない。','SUCCESS_RATE':'DAXELフラッシュはCZ成功回数が対象。'})
