const exactLive=new Set(['DIRECT_EXACT','EXACT_WITH_SCOPE_TRACKING','EXHAUSTIVE_CATEGORICAL','RETROSPECTIVE_EXACT']);
export function buildEligibility(e:any){return {schemaVersion:'eligibility-v1',manifestVersion:'8.5',batchId:e.batchId,machineId:e.machineId,machineName:e.machineName,decisions:(e.evaluations??[]).map((x:any)=>{
 if(x.model==='REFERENCE_ONLY'){const userFacingReason=Array.isArray(x.details)&&typeof x.details[0]==='string'&&x.details[0].trim()?x.details[0].trim():undefined;return {findingId:x.findingId,label:x.label,supportingSourceIds:x.sourceIds??[],eligibility:'NOT_APPLICABLE',reason:'参考分布として保存するが設定推測Featureには使用しない。',ruleRefs:['manifest-v8.5-reference-only'],liveInferenceRoute:'NONE',...(userFacingReason?{userFacingReason}:{}),...(x.reevaluationCondition?{reevaluationCondition:String(x.reevaluationCondition)}:{})};}
 if(x.model==='UNAVAILABLE')return {findingId:x.findingId,label:x.label,supportingSourceIds:x.sourceIds??[],eligibility:'UNRESOLVED',reason:'設定別分布が不完全なため現在は推測Featureにできない。',ruleRefs:['manifest-v8.5-source-completeness'],liveInferenceRoute:'NONE',reevaluationCondition:'不足している設定別分布がsource-supportedで揃うこと。'};
 const p=x.metrics?.igPerEligibleTrial;
 if(!(typeof p==='number'&&Number.isFinite(p))||p<=1e-15)return {findingId:x.findingId,label:x.label,supportingSourceIds:x.sourceIds??[],eligibility:'INELIGIBLE',reason:'設定間の情報量がない。',ruleRefs:['manifest-v8.5-information-gain'],liveInferenceRoute:'NONE'};
 if(exactLive.has(x.liveObservation?.status)&&x.dependency?.status!=='UNRESOLVED'&&!String(x.dependencyScopeAudit?.status??'').startsWith('UNRESOLVED_'))return {findingId:x.findingId,label:x.label,supportingSourceIds:x.sourceIds??[],eligibility:'ELIGIBLE',reason:'設定間の情報量があり、実戦で試行単位を再現可能に観測できる。',ruleRefs:['manifest-v8.5-information-gain','live-observation-contract'],liveInferenceRoute:'LIVE_CONDITIONAL'};
 return {findingId:x.findingId,label:x.label,supportingSourceIds:x.sourceIds??[],eligibility:'UNRESOLVED',reason:'情報量はあるが実戦観測または依存関係のContractが未解決。',ruleRefs:['manifest-v8.5-live-observation'],liveInferenceRoute:'NONE',reevaluationCondition:'試行単位を正確に観測できるContractまたは依存関係の解決方法が確立すること。'};
 }),blockedItems:e.blockedItems??[],evidenceCandidates:e.evidenceCandidates??[],sourceIntegrityIssues:[]};}
