import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';
import {buildDistribution} from './distribution-builder.ts';import {validateDistributionDocument} from './distribution-validator.ts';
const dir=path.resolve(process.argv[2]);const commit=process.argv[3],runId=process.argv[4]??'unknown';
if(!dir||!/^[0-9a-f]{40}$/.test(commit))throw new Error('USAGE: finalize-geass3-distribution <calibration-dir> <package-commit> <run-id>');
const read=(n:string)=>JSON.parse(fs.readFileSync(path.join(dir,n+'.json'),'utf8'));
const app=read('app_runtime'),pkg=read('machine_package');const appBytes=fs.readFileSync(path.join(dir,'app_runtime.json')),pkgBytes=fs.readFileSync(path.join(dir,'machine_package.json'));
const appRef={artifactId:'app-runtime-S_CODE_GEASS_3_CC_FS',kind:'app-runtime',path:'production/calibrations/code-geass3-cc-kallen-20261001/app_runtime.json',sha256:crypto.createHash('sha256').update(appBytes).digest('hex'),producerWorkId:'wrk_geass3_cc_kallen_zero_base_v2'};
const att={integration:{repository:'hanashinonetachou-arch/sloanalytica-data',branch:'prototype-multi-machine',commit,packagePath:'machines/S_CODE_GEASS_3_CC_FS/machine-package.json',catalogPath:'catalog.json'},package:{machineId:'S_CODE_GEASS_3_CC_FS',machineDataVersion:pkg.machine.machineDataVersion,settings:pkg.machine.settings,sha256:crypto.createHash('sha256').update(pkgBytes).digest('hex'),packageSizeBytes:pkgBytes.length,introductionDate:'2023-06-05',machineType:'MEDAL',gameType:'A_AT'},checks:{catalogIntegrity:true,pagesDeployment:{conclusion:'success',runId},uxContractAudit:{conclusion:'success'},machineIdentityConsistency:{batchMachineVerified:true,conclusion:'success'}}};
const dist=buildDistribution(app,appRef,att);validateDistributionDocument(dist,app,appRef);fs.writeFileSync(path.join(dir,'distribution.json'),JSON.stringify(dist,null,2)+'\n');fs.writeFileSync(path.join(dir,'distribution-attestation.json'),JSON.stringify(att,null,2)+'\n');console.log(JSON.stringify({machineId:dist.machineId,commit,sha256:att.package.sha256}));
