import fs from 'node:fs';
import crypto from 'node:crypto';
export const MACHINE_DATA_VALIDATOR_CONTRACT='machine-data-v1';
const canonical=(v:any):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).filter(k=>v[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const fail=(m:string):never=>{throw new Error('MACHINE_DATA_VALIDATION_FAILED:'+m)};
const settingKeys=(candidate:any)=>{const out=new Set<string>();for(const c of candidate?.candidates??[])for(const k of Object.keys(c?.settingDistribution??{}))out.add(k);return [...out].sort((a,b)=>Number(a)-Number(b))}
const researchSettingKeys=(research:any)=>{const out=new Set<string>();for(const f of research?.findings??[])for(const k of Object.keys(f?.settingDistribution??{}))out.add(k);return [...out].sort((a,b)=>Number(a)-Number(b))}
export function validateMachineDataDocument(doc:any,canonicalUi:any,candidate:any,observation:any,canonicalArtifact:any,candidateArtifact:any,observationArtifact:any,research:any=null,researchArtifact:any=null){
 if(doc?.schemaVersion!=='machine-data-v1'||doc?.manifestVersion!=='8.5')fail('HEADER');
 if(doc.batchId!==canonicalUi.batchId||doc.machineId!==canonicalUi.machineId||doc.machineId!==candidate.machineId||doc.machineId!==observation.machineId||doc.machineName!==canonicalUi.machineName)fail('IDENTITY');
 if(doc.provenance?.generationPath!=='V8_5_PRODUCTION_PIPELINE'||doc.provenance?.legacyOracleUsed!==false)fail('PROVENANCE');
 if(canonical(doc.sourceArtifacts?.canonicalUi)!==canonical(canonicalArtifact)||canonical(doc.sourceArtifacts?.candidateContract)!==canonical(candidateArtifact)||canonical(doc.sourceArtifacts?.observationEvidence)!==canonical(observationArtifact)||canonical(doc.sourceArtifacts?.research)!==canonical(researchArtifact))fail('LINKAGE');
 if(doc.packagePolicy?.offlineCapable!==true||doc.packagePolicy?.containsImages!==false||doc.packagePolicy?.containsExecutableCode!==false)fail('PACKAGE_POLICY');
 if(canonical(doc.uiContract)!==canonical(canonicalUi))fail('UI_COPY');
 const candidateKeys=settingKeys(candidate),keys=candidateKeys.length?candidateKeys:researchSettingKeys(research),expectedSettings={status:keys.length?'SOURCE_DERIVED':'UNRESOLVED',values:keys.map(k=>'SET_'+k)};if(canonical(doc.settings)!==canonical(expectedSettings))fail('SETTINGS');
 const sections=canonicalUi.numericSections??[],features=doc.features??[];if(!Array.isArray(features)||features.length!==sections.length)fail('FEATURE_COVERAGE');
 const cBy=new Map((candidate.candidates??[]).map((x:any)=>[x.findingId,x])),fBy=new Map(features.map((x:any)=>[x.findingId,x]));
 for(const s of sections){const c:any=cBy.get(s.sourceFindingId),f:any=fBy.get(s.sourceFindingId);if(!c||!f||c.runtimeInferenceAllowed!==true)fail('FEATURE_SOURCE:'+s.sourceFindingId);if(f.name!==s.title||f.model!==c.model||f.trialUniverse!==c.trialUniverse||f.runtimeInferenceAllowed!==true||canonical(f.settingDistribution)!==canonical(c.settingDistribution)||canonical(f.categoryModel)!==canonical(c.categoryModel)||canonical(f.runtimePolicyBinding)!==canonical(c.runtimePolicyBinding)||canonical(f.inputIds)!==canonical((s.inputs??[]).map((x:any)=>x.id))||canonical(f.score)!==canonical(s.score)||canonical(f.perEligibleTrialPower)!==canonical(s.perEligibleTrialPower))fail('FEATURE_COPY:'+s.sourceFindingId)}
 const heldIds=new Set((canonicalUi.heldObservations??[]).map((x:any)=>x.findingId));if(features.some((x:any)=>heldIds.has(x.findingId)))fail('HELD_MATERIALIZED');
 if(canonical(doc.evidence)!==canonical(canonicalUi.evidenceSections??[]))fail('EVIDENCE_COPY');if((doc.evidence??[]).some((x:any)=>x.runtimePolicyControlled!==false))fail('EVIDENCE_RUNTIME_POLICY');
 if(canonical(doc.heldObservations)!==canonical(canonicalUi.heldObservations??[]))fail('HELD_COPY');
 const expectedNonRuntime=JSON.parse(JSON.stringify((candidate.candidates??[]).filter((x:any)=>x.runtimeInferenceAllowed!==true).map((x:any)=>({findingId:x.findingId,label:x.label,dependencyResolution:x.dependencyResolution,resolvedIntoFindingId:x.resolvedIntoFindingId}))));
 if(canonical(doc.nonRuntimeCandidates??[])!==canonical(expectedNonRuntime))fail('NON_RUNTIME_CANDIDATES');
 if(canonical(doc.excludedDecisions??[])!==canonical(candidate.excludedDecisions??[]))fail('EXCLUDED_DECISIONS');
 if(canonical(doc.highLowDiscrimination)!==canonical(canonicalUi.machineInferenceSummary?.highLowDiscrimination))fail('HLD_COPY');
 if(canonical(doc.blockedItems)!==canonical(observation.blockedItems??[])||canonical(doc.sourceReferences)!==canonical(observation.sourceReferences??[]))fail('OBSERVATION_METADATA');
 return [{validator:MACHINE_DATA_VALIDATOR_CONTRACT,features:features.length,evidence:(doc.evidence??[]).length,held:(doc.heldObservations??[]).length,settingsStatus:doc.settings.status}];
}
export function validateMachineDataArtifacts(s:any,a:any,r:any){const out=r.producedArtifacts??[];if(out.length!==1)fail('OUTPUT_COUNT');const ref=out[0];if(ref.kind!=='machine-data'||typeof ref.path!=='string'||!ref.path.startsWith('production/batches/'+a.batchId+'/artifacts/'+a.machineId+'/machine_data/'))fail('OUTPUT_REF');const prefix='production/';const doc=s.read(...ref.path.slice(prefix.length).split('/'));const us=s.read('batches',a.batchId,'machines',a.machineId,'stages','CANONICAL_UI.json'),cs=s.read('batches',a.batchId,'machines',a.machineId,'stages','CANDIDATE_CONTRACT.json'),os=s.read('batches',a.batchId,'machines',a.machineId,'stages','OBSERVATION_EVIDENCE.json');if(!us.authoritativeOutputRef?.path||!cs.authoritativeOutputRef?.path||!os.authoritativeOutputRef?.path)fail('UPSTREAM_AUTHORITY_MISSING');const ui=s.read(...String(us.authoritativeOutputRef.path).slice(prefix.length).split('/')),candidate=s.read(...String(cs.authoritativeOutputRef.path).slice(prefix.length).split('/')),observation=s.read(...String(os.authoritativeOutputRef.path).slice(prefix.length).split('/'));const researchRel='batches/'+a.batchId+'/artifacts/'+a.machineId+'/research/result.json';const research=s.read(...researchRel.split('/'));const researchArtifact={artifactId:'research-'+a.machineId,kind:'research',path:'production/'+researchRel,sha256:crypto.createHash('sha256').update(fs.readFileSync(s.p(...researchRel.split('/')))).digest('hex'),producerWorkId:research.workId};return validateMachineDataDocument(doc,ui,candidate,observation,us.authoritativeOutputRef,cs.authoritativeOutputRef,os.authoritativeOutputRef,research,researchArtifact)}
