import fs from 'node:fs';import crypto from 'node:crypto';
export const RUNTIME_POLICY_VALIDATOR_CONTRACT='runtime-policy-v1';
const canonical=(v:any):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const fail=(m:string):never=>{throw new Error('RUNTIME_POLICY_VALIDATION_FAILED:'+m)};
export function validateRuntimePolicyDocument(doc:any,machineData:any,config:any,machineDataArtifact:any,configArtifact:any=null){
 if(doc?.schemaVersion!=='runtime-policy-v1'||doc?.manifestVersion!=='8.5')fail('HEADER');if(doc.batchId!==machineData.batchId||doc.machineId!==machineData.machineId||doc.machineName!==machineData.machineName)fail('IDENTITY');
 if(canonical(doc.sourceArtifacts?.machineData)!==canonical(machineDataArtifact)||canonical(doc.sourceArtifacts?.policyConfig)!==canonical(configArtifact))fail('LINKAGE');
 const features=machineData.features??[];
 if(features.length===0){if(config!==null)fail('UNNECESSARY_CONFIG');if(doc.thresholdRequirement!=='NOT_APPLICABLE_NO_RUNTIME_FEATURES'||doc.thresholds!==null||!Array.isArray(doc.featureDecisions)||doc.featureDecisions.length!==0)fail('NO_FEATURE_POLICY')}else{
  if(!config||config.schemaVersion!=='runtime-policy-config-v1'||config.manifestVersion!=='8.5')fail('CONFIG_REQUIRED');if(doc.thresholdRequirement!=='REQUIRED'||canonical(doc.thresholds)!==canonical(config.thresholds))fail('THRESHOLDS');
  if(!Array.isArray(doc.featureDecisions)||doc.featureDecisions.length!==features.length)fail('DECISION_COVERAGE');const by=new Map(doc.featureDecisions.map((x:any)=>[x.findingId,x]));
  for(const f of features){const d:any=by.get(f.findingId),metric=f.runtimePolicyBinding?.metric,value=f.runtimePolicyBinding?.value,rule=config.thresholds?.[metric];if(!d||!rule||rule.status!=='FIXED'||typeof rule.value!=='number')fail('THRESHOLD:'+f.findingId);if(d.metric!==metric||d.value!==value||d.threshold!==rule.value||d.state!==(value>=rule.value?'ACTIVE':'INACTIVE'))fail('DECISION:'+f.findingId)}
 }
 if(doc.evidencePolicy?.runtimePolicyControlled!==false||doc.evidencePolicy?.evidenceCount!==(machineData.evidence??[]).length)fail('EVIDENCE_POLICY');if(canonical(doc.heldObservations)!==canonical(machineData.heldObservations??[]))fail('HELD_COPY');
 return [{validator:RUNTIME_POLICY_VALIDATOR_CONTRACT,features:features.length,active:(doc.featureDecisions??[]).filter((x:any)=>x.state==='ACTIVE').length,inactive:(doc.featureDecisions??[]).filter((x:any)=>x.state==='INACTIVE').length,evidence:(machineData.evidence??[]).length}];
}
export function validateRuntimePolicyArtifacts(s:any,a:any,r:any){const out=r.producedArtifacts??[];if(out.length!==1)fail('OUTPUT_COUNT');const ref=out[0];if(ref.kind!=='runtime-policy'||typeof ref.path!=='string'||!ref.path.startsWith('production/batches/'+a.batchId+'/artifacts/'+a.machineId+'/runtime_policy/'))fail('OUTPUT_REF');const prefix='production/';const doc=s.read(...ref.path.slice(prefix.length).split('/')),ms=s.read('batches',a.batchId,'machines',a.machineId,'stages','MACHINE_DATA.json');if(!ms.authoritativeOutputRef?.path)fail('MACHINE_DATA_AUTHORITY_MISSING');const machineData=s.read(...String(ms.authoritativeOutputRef.path).slice(prefix.length).split('/'));let config=null,configArtifact=null;const rel=['batches',a.batchId,'runtime-policy-config.json'];const full=s.p(...rel);if(fs.existsSync(full)){config=s.read(...rel);configArtifact={artifactId:'runtime-policy-config-'+a.batchId,kind:'runtime-policy-config',path:'production/batches/'+a.batchId+'/runtime-policy-config.json',sha256:crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex'),producerWorkId:'HUMAN_POLICY'}}return validateRuntimePolicyDocument(doc,machineData,config,ms.authoritativeOutputRef,configArtifact)}
