import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
import {RepoStore,Orchestrator,dispatchable,schedule,fingerprint} from './core.ts';
import type {Stage,WorkRequest,WorkResult,Concurrency} from './core.ts';
import {validateResearchArtifacts,RESEARCH_VALIDATOR_CONTRACT} from './research-validator.ts';
import {validateEvaluationArtifacts,EVALUATION_VALIDATOR_CONTRACT} from './evaluation-validator.ts';
import {validateEligibilityArtifacts,ELIGIBILITY_VALIDATOR_CONTRACT} from './eligibility-validator.ts';
import {validateCandidateContractArtifacts,CANDIDATE_CONTRACT_VALIDATOR_CONTRACT} from './candidate-contract-validator.ts';
import {validateObservationEvidenceArtifacts,OBSERVATION_EVIDENCE_VALIDATOR_CONTRACT} from './observation-evidence-validator.ts';

export const PRODUCTION_STAGES=[
  'RESEARCH','EVALUATION','ELIGIBILITY','CANDIDATE_CONTRACT','OBSERVATION_EVIDENCE',
  'CANONICAL_UI','MACHINE_DATA','RUNTIME_POLICY','RUNTIME_PROJECTION','APP_RUNTIME','DISTRIBUTION','DEVICE_QA'
] as const;
export type ProductionStage=typeof PRODUCTION_STAGES[number];
export type WorkerKind='SEMANTIC'|'PRODUCTION'|'VALIDATOR'|'INTEGRATION'|'HUMAN';
export const STAGE_WORKER:Record<ProductionStage,WorkerKind>={
 RESEARCH:'SEMANTIC',EVALUATION:'SEMANTIC',ELIGIBILITY:'SEMANTIC',CANDIDATE_CONTRACT:'SEMANTIC',
 OBSERVATION_EVIDENCE:'SEMANTIC',CANONICAL_UI:'SEMANTIC',MACHINE_DATA:'PRODUCTION',RUNTIME_POLICY:'PRODUCTION',
 RUNTIME_PROJECTION:'PRODUCTION',APP_RUNTIME:'PRODUCTION',DISTRIBUTION:'INTEGRATION',DEVICE_QA:'HUMAN'};
export interface BatchSpec{batchId:string;manifestVersion:string;waves:{waveId:string;machineIds:string[]}[]}
export interface ArtifactRef{artifactId:string;kind:string;path:string;sha256:string;producerWorkId:string}
export interface ProvenanceRecord{workId:string;attemptId:string;machineId:string;stage:string;inputArtifacts:ArtifactRef[];outputArtifacts:ArtifactRef[];workerAdapter:string;validatorAdapter:string;recordedAt:string}
export interface WorkerAdapter{kind:'SEMANTIC'|'PRODUCTION'|'INTEGRATION';execute(q:WorkRequest):Promise<WorkResult>|WorkResult}
export interface ValidatorAdapter{name:string;validate(r:WorkResult):{ok:boolean;evidence:any[]}}
export const ARTIFACT_KIND:Record<ProductionStage,string>={RESEARCH:'research',EVALUATION:'evaluation',ELIGIBILITY:'eligibility',CANDIDATE_CONTRACT:'candidate-contract',OBSERVATION_EVIDENCE:'observation-evidence',CANONICAL_UI:'canonical-ui',MACHINE_DATA:'machine-data',RUNTIME_POLICY:'runtime-policy',RUNTIME_PROJECTION:'runtime-projection',APP_RUNTIME:'app-runtime',DISTRIBUTION:'distribution',DEVICE_QA:'device-qa'};
export function expectedArtifact(b:string,m:string,stage:ProductionStage){return {kind:ARTIFACT_KIND[stage],pathPrefix:`production/batches/${b}/artifacts/${m}/${stage.toLowerCase()}/`}}
export function productionRequest(o:Orchestrator,x:Stage,a:any,l:any,manifestVersion='8.5'){const q=o.request(x,a,l);const stage=x.name as ProductionStage;q.workerType=STAGE_WORKER[stage];q.manifestVersion=manifestVersion;q.expectedOutputs=[expectedArtifact(x.batchId,x.machineId,stage)];q.validatorContractVersion=stage==='RESEARCH'?RESEARCH_VALIDATOR_CONTRACT:stage==='EVALUATION'?EVALUATION_VALIDATOR_CONTRACT:stage==='ELIGIBILITY'?ELIGIBILITY_VALIDATOR_CONTRACT:stage==='CANDIDATE_CONTRACT'?CANDIDATE_CONTRACT_VALIDATOR_CONTRACT:stage==='OBSERVATION_EVIDENCE'?OBSERVATION_EVIDENCE_VALIDATOR_CONTRACT:'mock-1';if(stage==='EVALUATION'){const rel=`batches/${x.batchId}/artifacts/${x.machineId}/research/result.json`;const full=o.s.p(rel);const doc=JSON.parse(fs.readFileSync(full,'utf8'));q.inputArtifacts=[{artifactId:`research-${x.machineId}`,kind:'research',path:`production/${rel}`,sha256:crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex'),producerWorkId:doc.workId}]}if(stage==='OBSERVATION_EVIDENCE'){const cs=o.stage(x.batchId,x.machineId,'CANDIDATE_CONTRACT');const cr=cs.authoritativeOutputRef;if(!cr?.path)throw new Error('CANDIDATE_AUTHORITY_REQUIRED');const rel=String(cr.path).startsWith('production/')?String(cr.path).slice('production/'.length):String(cr.path);const full=o.s.p(rel);q.inputArtifacts=[{...cr,sha256:crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex')}]} 
if(stage==='CANDIDATE_CONTRACT'){const gs=o.stage(x.batchId,x.machineId,'ELIGIBILITY');const es=o.stage(x.batchId,x.machineId,'EVALUATION');const gr=gs.authoritativeOutputRef,er=es.authoritativeOutputRef;if(!gr?.path||!er?.path)throw new Error('CANDIDATE_UPSTREAM_AUTHORITY_REQUIRED');q.inputArtifacts=[gr,er].map((z:any)=>{const rel=String(z.path).startsWith('production/')?String(z.path).slice('production/'.length):String(z.path);const full=o.s.p(rel);return {...z,sha256:crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex')}})}
if(stage==='ELIGIBILITY'){const researchRel=`batches/${x.batchId}/artifacts/${x.machineId}/research/result.json`;const researchFull=o.s.p(researchRel);const research=JSON.parse(fs.readFileSync(researchFull,'utf8'));const es=o.stage(x.batchId,x.machineId,'EVALUATION');const er=es.authoritativeOutputRef;if(!er?.path)throw new Error('EVALUATION_AUTHORITATIVE_OUTPUT_REQUIRED');const evalRel=String(er.path).startsWith('production/')?String(er.path).slice('production/'.length):String(er.path);const evalFull=o.s.p(evalRel);q.inputArtifacts=[{artifactId:`research-${x.machineId}`,kind:'research',path:`production/${researchRel}`,sha256:crypto.createHash('sha256').update(fs.readFileSync(researchFull)).digest('hex'),producerWorkId:research.workId},{...er,sha256:crypto.createHash('sha256').update(fs.readFileSync(evalFull)).digest('hex')}]}return q}
export function acceptAndRecord(o:Orchestrator,s:RepoStore,r:WorkResult,workerAdapter:string,validatorAdapter:string){const a=o.findAttempt(o.findBatch(r),r.attemptId);if(!a)throw new Error('UNKNOWN_ATTEMPT');const stage=a.stage as ProductionStage;const expected=expectedArtifact(a.batchId,a.machineId,stage);const outputs=(r.producedArtifacts||[]) as ArtifactRef[];if(r.status==='SUCCESS'&&outputs.some(x=>x.kind!==expected.kind||!x.path.startsWith(expected.pathPrefix)||x.producerWorkId!==r.workId))throw new Error('ARTIFACT_CONTRACT_VIOLATION');if(stage==='RESEARCH'&&r.status==='SUCCESS')r.validationEvidence=validateResearchArtifacts(s,a,r);
if(stage==='EVALUATION'&&r.status==='SUCCESS')r.validationEvidence=validateEvaluationArtifacts(s,a,r);if(stage==='ELIGIBILITY'&&r.status==='SUCCESS')r.validationEvidence=validateEligibilityArtifacts(s,a,r);if(stage==='CANDIDATE_CONTRACT'&&r.status==='SUCCESS')r.validationEvidence=validateCandidateContractArtifacts(s,a,r);if(stage==='OBSERVATION_EVIDENCE'&&r.status==='SUCCESS')r.validationEvidence=validateObservationEvidenceArtifacts(s,a,r);if(r.status==='HUMAN_REQUIRED'){if(!Array.isArray(r.requestedActions)||r.requestedActions.length===0)throw new Error('HUMAN_ACTION_REQUIRED');for(const x of r.requestedActions)if(typeof x?.actionId!=='string'||typeof x?.type!=='string'||typeof x?.question!=='string')throw new Error('INVALID_HUMAN_ACTION')}const accepted=o.accept(r);if(accepted.kind==='COMMITTED')appendProvenance(s,accepted.stage.batchId,{workId:r.workId,attemptId:r.attemptId,machineId:accepted.stage.machineId,stage,inputArtifacts:(r.provenance?.inputArtifacts??[]),outputArtifacts:outputs,workerAdapter,validatorAdapter,recordedAt:o.now().toISOString()});if(accepted.kind==='HUMAN_REQUIRED')for(const x of r.requestedActions)s.write({...x,batchId:accepted.stage.batchId,machineId:accepted.stage.machineId,stage,status:'OPEN',createdAt:o.now().toISOString()},'batches',accepted.stage.batchId,'action-requests',x.actionId+'.json');return accepted}
export const deps=(stage:ProductionStage)=>{const i=PRODUCTION_STAGES.indexOf(stage);return i===0?[]:[PRODUCTION_STAGES[i-1]]}
export function initializeBatch(s:RepoStore,spec:BatchSpec,contract='production-1'){
 const ids=spec.waves.flatMap(w=>w.machineIds);
 if(spec.waves.length!==2||spec.waves.some(w=>w.machineIds.length!==5)||ids.length!==10||new Set(ids).size!==10)throw new Error('INVALID_BATCH_SHAPE');
 s.write(spec,'batches',spec.batchId,'batch.json');
 for(const w of spec.waves){s.write(w,'batches',spec.batchId,'waves',w.waveId+'.json');for(const m of w.machineIds){
  s.write({machineId:m,waveId:w.waveId},'batches',spec.batchId,'machines',m,'machine.json');
  for(const name of PRODUCTION_STAGES){const x:Stage={batchId:spec.batchId,machineId:m,name,state:name==='RESEARCH'?'READY':'PENDING',revision:0,dependencies:deps(name),authoritativeInputFingerprint:fingerprint({machineId:m,stage:name,manifestVersion:spec.manifestVersion}),contractVersion:contract};s.write(x,'batches',spec.batchId,'machines',m,'stages',name+'.json')}
 }}}
export function promoteDependencies(o:Orchestrator,b:string,m:string){for(const name of PRODUCTION_STAGES){let x=o.stage(b,m,name);if(x.state==='PENDING'&&x.dependencies.every(d=>o.stage(b,m,d).state==='COMPLETE'))o.transition(x,'READY','DEPENDENCY_COMPLETE',x.dependencies.join(','))}}
export function appendProvenance(s:RepoStore,b:string,p:ProvenanceRecord){s.append(p,'batches',b,'provenance','chain.jsonl')}
export function dashboard(s:RepoStore,b:string){const md=s.p('batches',b,'machines');const machines=fs.readdirSync(md).sort().map(machineId=>{const stages=PRODUCTION_STAGES.map(name=>s.read<Stage>('batches',b,'machines',machineId,'stages',name+'.json'));const active=stages.find(x=>!['PENDING','COMPLETE'].includes(x.state))??stages.at(-1)!;return {machineId,stage:active.name,state:active.state,revision:active.revision,blocked:active.state==='WAIT_EXTERNAL'||active.state==='HUMAN_REQUIRED',failed:active.state==='FAILED'}});return {batchId:b,machines,counts:machines.reduce((a,x)=>(a[x.state]=(a[x.state]||0)+1,a),{} as Record<string,number>)}}
export function reconcileBatch(o:Orchestrator,s:RepoStore,b:string){const md=s.p('batches',b,'machines');for(const m of fs.readdirSync(md)){for(const n of PRODUCTION_STAGES)o.reconcile(b,m,n);promoteDependencies(o,b,m)}return dashboard(s,b)}
const RESEARCH_WAVE_SETTLED=new Set(['COMPLETE','FAILED','WAIT_EXTERNAL','HUMAN_REQUIRED']);
export function activeResearchWave(s:RepoStore,b:string){const spec=s.read<BatchSpec>('batches',b,'batch.json');for(const w of spec.waves){if(w.machineIds.some(m=>!RESEARCH_WAVE_SETTLED.has(s.read<Stage>('batches',b,'machines',m,'stages','RESEARCH.json').state)))return w.waveId}return undefined}
export function scheduleByKind(o:Orchestrator,s:RepoStore,b:string,c:Concurrency,kind:Exclude<WorkerKind,'VALIDATOR'|'HUMAN'>){const all:Record<string,Stage>={};const candidates:Stage[]=[];const spec=s.read<BatchSpec>('batches',b,'batch.json');const activeWave=activeResearchWave(s,b);const researchIds=new Set(spec.waves.find(w=>w.waveId===activeWave)?.machineIds??[]);for(const m of fs.readdirSync(s.p('batches',b,'machines'))){for(const n of PRODUCTION_STAGES){const x=o.stage(b,m,n);all[m+':'+n]=x;if(STAGE_WORKER[n]===kind&&(n!=='RESEARCH'||researchIds.has(m))&&!(kind==='SEMANTIC'&&activeWave&&n!=='RESEARCH'))candidates.push({...x,dependencies:x.dependencies.map(d=>m+':'+d)})}}const slots=kind==='SEMANTIC'?c.semanticSlots:kind==='PRODUCTION'?c.productionSlots:c.integrationSlots;return schedule(candidates,all,slots,o.now()).map(x=>({...x,dependencies:x.dependencies.map(d=>d.split(':').at(-1)!)}))}