import test from 'node:test';import assert from 'node:assert/strict';import {buildAppRuntime} from '../src/app-runtime-builder.ts';import {validateAppRuntimeDocument} from '../src/app-runtime-validator.ts';
const ref={path:'p'};
const base={batchId:'batch-x',machineId:'M',machineName:'Machine',activeFeatures:[],inactiveFeatures:[],settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2']},packagePolicy:{offlineCapable:true},evidence:[],heldObservations:[{findingId:'h',label:'Held',status:'HELD_NO_JOINT_MODEL'}],highLowDiscrimination:{status:'NOT_COMPUTED',reason:'x'},runtimeUi:{schemaVersion:'canonical-ui-v1',playInfo:{visible:true,useDifference:{label:'着席時との差分を使用'}},numericSections:[],evidenceSections:[]}};
test('builds app-compatible reference-only package',()=>{const d=buildAppRuntime(base,ref);assert.equal(d.package.schemaVersion,1);assert.equal(d.package.ui.contractVersion,'runtime-ui-v8');assert.equal(d.package.features.features.length,0);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,base,ref))});
test('fails closed for unresolved settings',()=>{assert.throws(()=>buildAppRuntime({...base,settings:{status:'UNRESOLVED',values:[]}},ref),/SETTINGS_REQUIRED/)});
test('materializes active Bernoulli feature and play-data binding',()=>{const p:any={...base,activeFeatures:[{findingId:'f',name:'CZ初当り',model:'BERNOULLI',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':'1/200','2':'1/150'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:2},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_f',sourceFindingId:'f',title:'CZ初当り',inputs:[{id:'f.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'f.successCount',label:'該当回数',role:'success',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.features.features[0].modelType,'binomial');assert.equal(d.package.inputs.inputs.length,2);assert.equal(d.package.ui.v8Sections[0].items[0].inputs[0].label,'通常ゲーム数');assert.equal(d.package.ui.v8Sections[0].items[0].inputs[1].label,'回数');assert.equal(d.package.ui.v8Sections[0].items[0].inputs[0].playDataBinding.source,'PLAY_NORMAL_GAME_DELTA');assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});
test('materializes active categorical feature with explicit opportunity count',()=>{const p:any={...base,activeFeatures:[{findingId:'j',name:'終了画面',model:'CATEGORICAL',trialUniverse:'AT_END_SCREEN_TRIAL',settingDistribution:{'1':{'弱':0.2,'強':0.1},'2':{'弱':0.3,'強':0.2}},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:4},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_j',sourceFindingId:'j',title:'終了画面',inputs:[{id:'j.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'j.categoryCounts.1_弱',label:'弱',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.2_強',label:'強',role:'categoryCount',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.features.features[0].modelType,'multinomial');assert.deepEqual(d.package.features.features[0].categoryProbabilities.SET_1,[0.2,0.1]);assert.equal(d.package.ui.v8Sections[0].items[0].interaction.opportunityTracking.inputId,'j.eligibleTrialCount');assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('publishes computed HLD and removes unresolved HLD entry',()=>{const p:any={...base,highLowDiscrimination:{status:'COMPUTED',method:'BEST_SINGLE_EXACT_ACTIVE_FEATURE',results:[{games:1500,balancedAccuracyPercent:60.1},{games:3000,balancedAccuracyPercent:64.2},{games:7000,balancedAccuracyPercent:71.3}],selectedFeatureId:'f',eligibleFeatureIds:['f'],excludedFeatures:[]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.v8.machineResearchSummary.highLowDiscrimination.status,'COMPUTED');assert.equal(d.package.v8.machineResearchSummary.unresolved.length,0);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('normalizes source string categorical rows including explicit residual category',()=>{const p:any={...base,activeFeatures:[{findingId:'j',name:'振り分け',model:'CATEGORICAL',trialUniverse:'EVENT_TRIAL',settingDistribution:{'1':'勝40% / 鳴海60%','2':'勝60% / 鳴海40%'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:4},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_j',sourceFindingId:'j',title:'振り分け',inputs:[{id:'j.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'j.categoryCounts.1_勝',label:'勝',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.2_鳴海',label:'鳴海',role:'categoryCount',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.features.features[0].categoryProbabilities.SET_1,[0.4,0.6]);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});
test('derives その他 from source string residual mass',()=>{const p:any={...base,activeFeatures:[{findingId:'j',name:'振り分け',model:'CATEGORICAL',trialUniverse:'EVENT_TRIAL',settingDistribution:{'1':'+20:5% / +4:0% / +6:0%','2':'+20:3% / +4:5% / +6:0%'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:4},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_j',sourceFindingId:'j',title:'振り分け',inputs:[{id:'j.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'j.categoryCounts.1_20',label:'+20',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.2_4',label:'+4',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.3_6',label:'+6',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.4_other',label:'その他',role:'categoryCount',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.features.features[0].categoryProbabilities.SET_1,[0.05,0,0,0.95]);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('materializes every setting-hint reference into package and recordable v8 UI',()=>{const ev={id:'EVI_e',sourceFindingId:'e',title:'終了画面',description:'設定示唆として参照します。',runtimePolicyControlled:false,evidenceItems:[{findingId:'e',label:'終了画面',details:['茶屋：偶数設定示唆']}]};const p:any={...base,evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.evidence.evidences.length,1);assert.equal(d.package.evidence.evidences[0].id,'e');assert.equal(d.package.evidence.evidences[0].type,'REFERENCE_ONLY');assert.deepEqual(d.package.evidence.evidences[0].details,['茶屋：偶数設定示唆']);const s=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_e');assert.doesNotMatch(s.description,/Evidence/i);assert.equal(s.items[0].interaction.type,'REFERENCE_MULTI_SELECT');assert.equal(d.package.inputs.inputs.find((x:any)=>x.id==='REF_e').type,'multi_enum');assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('preserves resolved and ineligible decisions in not-adopted summary',()=>{const p:any={...base,nonRuntimeCandidates:[{findingId:'cz',label:'CZ初当り',dependencyResolution:'RESOLVED_BY_SINGLE_MEMBER',resolvedIntoFindingId:'bonus'}],excludedDecisions:[{findingId:'partial',label:'CZ成功率',reason:'設定別likelihoodが不完全。',reevaluationCondition:'全設定値が公開されること。'}]};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.v8.machineResearchSummary.notAdopted.map((x:any)=>x.featureId),['h','cz','partial']);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('renders setting-hint guidance once at section level',()=>{const ev={id:'EVI_e',sourceFindingId:'e',title:'終了画面',description:'設定示唆として参照します。',runtimePolicyControlled:false,evidenceItems:[{findingId:'e',label:'終了画面',details:[]}]};const p:any={...base,evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);const s=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_e');assert.match(s.description,/設定示唆/);assert.doesNotMatch(s.description,/Evidence/i);assert.equal(s.items[0].description,undefined);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('keeps internal runtime terminology out of research summary copy',()=>{const p:any={...base,activeFeatures:[{findingId:'f',name:'CZ初当り',model:'BERNOULLI',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':'1/200','2':'1/150'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:2},score:{status:'NOT_COMPUTED'}}],inactiveFeatures:[{findingId:'i',name:'AT初当り',metric:'SELECTION_SCORE',value:4,threshold:5}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_f',sourceFindingId:'f',title:'CZ初当り',inputs:[{id:'f.eligibleTrialCount',label:'観測機会数',role:'trial'},{id:'f.successCount',label:'該当回数',role:'success'}]}]}};const d=buildAppRuntime(p,ref);const text=JSON.stringify(d.package.v8.machineResearchSummary);assert.doesNotMatch(text,/Runtime Policy|joint model/i);assert.match(text,/現在の採用基準/);});


test('fails closed when v8.5 play-data difference control is not declared',()=>{const p:any={...base,runtimeUi:{...base.runtimeUi,playInfo:undefined}};const d=buildAppRuntime(p,ref);assert.throws(()=>validateAppRuntimeDocument(d,p,ref),/UI_PLAY_INFO/)});
