import test from 'node:test';import assert from 'node:assert/strict';import {buildAppRuntime} from '../src/app-runtime-builder.ts';import {validateAppRuntimeDocument} from '../src/app-runtime-validator.ts';
const ref={path:'p'};
const base={batchId:'batch-x',machineId:'M',machineName:'Machine',activeFeatures:[],inactiveFeatures:[],settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2']},packagePolicy:{offlineCapable:true},evidence:[],heldObservations:[{findingId:'h',label:'Held',status:'HELD_NO_JOINT_MODEL'}],highLowDiscrimination:{status:'NOT_COMPUTED',reason:'x'},runtimeUi:{schemaVersion:'canonical-ui-v1',playInfo:{visible:true,useDifference:{label:'着席時との差分を使用'}},numericSections:[],evidenceSections:[]}};
test('builds app-compatible reference-only package',()=>{const d=buildAppRuntime(base,ref);assert.equal(d.package.schemaVersion,1);assert.equal(d.package.ui.contractVersion,'runtime-ui-v8');assert.equal(d.package.features.features.length,0);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,base,ref))});
test('fails closed for unresolved settings',()=>{assert.throws(()=>buildAppRuntime({...base,settings:{status:'UNRESOLVED',values:[]}},ref),/SETTINGS_REQUIRED/)});
test('materializes active Bernoulli feature and play-data binding',()=>{const p:any={...base,activeFeatures:[{findingId:'f',name:'CZ初当り',model:'BERNOULLI',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':'1/200','2':'1/150'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:2},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_f',sourceFindingId:'f',title:'CZ初当り',inputs:[{id:'f.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'f.successCount',label:'該当回数',role:'success',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.features.features[0].modelType,'binomial');assert.equal(d.package.inputs.inputs.length,2);assert.equal(d.package.ui.v8Sections[0].items[0].inputs[0].label,'通常ゲーム数');assert.equal(d.package.ui.v8Sections[0].items[0].inputs[1].label,'回数');assert.equal(d.package.ui.v8Sections[0].items[0].inputs[0].playDataBinding.source,'PLAY_NORMAL_GAME_DELTA');assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});
test('materializes active categorical feature with explicit opportunity count',()=>{const p:any={...base,activeFeatures:[{findingId:'j',name:'終了画面',model:'CATEGORICAL',trialUniverse:'AT_END_SCREEN_TRIAL',settingDistribution:{'1':{'弱':0.2,'強':0.1},'2':{'弱':0.3,'強':0.2}},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:4},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_j',sourceFindingId:'j',title:'終了画面',inputs:[{id:'j.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'j.categoryCounts.1_弱',label:'弱',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.2_強',label:'強',role:'categoryCount',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.features.features[0].modelType,'multinomial');assert.deepEqual(d.package.features.features[0].categoryProbabilities.SET_1,[0.2,0.1]);assert.equal(d.package.ui.v8Sections[0].items[0].interaction.opportunityTracking.inputId,'j.eligibleTrialCount');assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('publishes computed HLD and removes unresolved HLD entry',()=>{const p:any={...base,highLowDiscrimination:{status:'COMPUTED',method:'BEST_SINGLE_EXACT_ACTIVE_FEATURE',results:[{games:1500,balancedAccuracyPercent:60.1},{games:3000,balancedAccuracyPercent:64.2},{games:7000,balancedAccuracyPercent:71.3}],selectedFeatureId:'f',eligibleFeatureIds:['f'],excludedFeatures:[]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.v8.machineResearchSummary.highLowDiscrimination.status,'COMPUTED');assert.equal(d.package.v8.machineResearchSummary.unresolved.length,0);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('normalizes source string categorical rows including explicit residual category',()=>{const p:any={...base,activeFeatures:[{findingId:'j',name:'振り分け',model:'CATEGORICAL',trialUniverse:'EVENT_TRIAL',settingDistribution:{'1':'勝40% / 鳴海60%','2':'勝60% / 鳴海40%'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:4},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_j',sourceFindingId:'j',title:'振り分け',inputs:[{id:'j.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'j.categoryCounts.1_勝',label:'勝',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.2_鳴海',label:'鳴海',role:'categoryCount',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.features.features[0].categoryProbabilities.SET_1,[0.4,0.6]);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});
test('derives その他 from source string residual mass',()=>{const p:any={...base,activeFeatures:[{findingId:'j',name:'振り分け',model:'CATEGORICAL',trialUniverse:'EVENT_TRIAL',settingDistribution:{'1':'+20:5% / +4:0% / +6:0%','2':'+20:3% / +4:5% / +6:0%'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:4},score:{status:'NOT_COMPUTED'}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_j',sourceFindingId:'j',title:'振り分け',inputs:[{id:'j.eligibleTrialCount',label:'観測機会数',role:'trial',quickAdd:[50]},{id:'j.categoryCounts.1_20',label:'+20',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.2_4',label:'+4',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.3_6',label:'+6',role:'categoryCount',quickAdd:[1]},{id:'j.categoryCounts.4_other',label:'その他',role:'categoryCount',quickAdd:[1]}]}]}};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.features.features[0].categoryProbabilities.SET_1,[0.05,0,0,0.95]);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('keeps vague setting hints as repeatable counters without inventing probability weights',()=>{const ev={id:'EVI_e',sourceFindingId:'e',title:'終了画面',description:'設定示唆として参照します。',runtimePolicyControlled:false,evidenceItems:[{findingId:'e',label:'終了画面',semanticType:'PROBABILITY_UNKNOWN',details:['茶屋：偶数設定示唆','街道：奇数設定示唆']}]};const p:any={...base,evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.evidence.evidences.length,0);const s=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_e');assert.doesNotMatch(s.description,/Evidence/i);assert.match(s.description,/設定別の出現率が公表・確認されていない/);assert.match(s.description,/現在の設定推測計算には直接反映していません/);assert.match(s.description,/反映できる可能性があります/);assert.doesNotMatch(s.description,/反映できます。/);assert.equal(s.items[0].interaction.type,'CATEGORY_COUNTERS');assert.equal(s.items[0].interaction.categories.length,2);assert.equal(d.package.inputs.inputs.find((x:any)=>x.id==='REF_e_1').type,'counter');assert.equal(d.package.inputs.inputs.find((x:any)=>x.id==='REF_e_2').inferenceRole,'DISPLAY_ONLY');assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('materializes source-grounded setting constraints for EvidenceEngine',()=>{const ev={id:'EVI_e',sourceFindingId:'e',title:'示唆',description:'x',runtimePolicyControlled:false,evidenceItems:[{findingId:'e',label:'示唆',semanticType:'EXACT_CONSTRAINT',details:['金：設定4以上','青：設定2否定','虹：設定6']}]};const p:any={...base,settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2','SET_3','SET_4','SET_5','SET_6']},evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.evidence.evidences.length,3);assert.deepEqual(d.package.evidence.evidences[0].confirmedSettings,['SET_4','SET_5','SET_6']);assert.deepEqual(d.package.evidence.evidences[1].deniedSettings,['SET_2']);assert.deepEqual(d.package.evidence.evidences[2].confirmedSettings,['SET_6']);assert.equal(d.package.evidence.evidences[0].inputId,'REF_e_1');const s=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_e');assert.match(s.description,/設定候補の絞り込みに反映/);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('preserves resolved and ineligible decisions in not-adopted summary',()=>{const p:any={...base,nonRuntimeCandidates:[{findingId:'cz',label:'CZ初当り',dependencyResolution:'RESOLVED_BY_SINGLE_MEMBER',resolvedIntoFindingId:'bonus'}],excludedDecisions:[{findingId:'partial',label:'CZ成功率',reason:'設定別likelihoodが不完全。',reevaluationCondition:'全設定値が公開されること。'}]};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.v8.machineResearchSummary.notAdopted.map((x:any)=>x.featureId),['h','cz','partial']);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('renders setting-hint guidance once at section level',()=>{const ev={id:'EVI_e',sourceFindingId:'e',title:'終了画面',description:'設定示唆として参照します。',runtimePolicyControlled:false,evidenceItems:[{findingId:'e',label:'終了画面',semanticType:'PROBABILITY_UNKNOWN',details:[]}]};const p:any={...base,evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);const s=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_e');assert.match(s.description,/設定示唆/);assert.doesNotMatch(s.description,/Evidence/i);assert.equal(s.items[0].description,undefined);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('keeps internal runtime terminology out of research summary copy',()=>{const p:any={...base,activeFeatures:[{findingId:'f',name:'CZ初当り',model:'BERNOULLI',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':'1/200','2':'1/150'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:2},score:{status:'NOT_COMPUTED'}}],inactiveFeatures:[{findingId:'i',name:'AT初当り',metric:'SELECTION_SCORE',value:4,threshold:5}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_f',sourceFindingId:'f',title:'CZ初当り',inputs:[{id:'f.eligibleTrialCount',label:'観測機会数',role:'trial'},{id:'f.successCount',label:'該当回数',role:'success'}]}]}};const d=buildAppRuntime(p,ref);const text=JSON.stringify(d.package.v8.machineResearchSummary);assert.doesNotMatch(text,/Runtime Policy|joint model/i);assert.match(text,/現在の採用基準/);});


test('fails closed when v8.5 play-data difference control is not declared',()=>{const p:any={...base,runtimeUi:{...base.runtimeUi,playInfo:undefined}};const d=buildAppRuntime(p,ref);assert.throws(()=>validateAppRuntimeDocument(d,p,ref),/UI_PLAY_INFO/)});

test('materializes enumerated explicit setting constraints without invented weights',()=>{const ev={id:'EVI_e',sourceFindingId:'e',title:'示唆',description:'x',runtimePolicyControlled:false,evidenceItems:[{findingId:'e',label:'示唆',semanticType:'EXACT_CONSTRAINT',details:['246枚：設定2・4・6','舞坂：設定1・5・6濃厚']}]};const p:any={...base,settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2','SET_3','SET_4','SET_5','SET_6']},evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.evidence.evidences[0].confirmedSettings,['SET_2','SET_4','SET_6']);assert.deepEqual(d.package.evidence.evidences[1].confirmedSettings,['SET_1','SET_5','SET_6']);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});

test('mixed Evidence materializes only exact category and keeps directional category reference-only',()=>{const ev:any={id:'EVI_mix',sourceFindingId:'mix',title:'終了画面',runtimePolicyControlled:false,evidenceItems:[{findingId:'mix',label:'終了画面',semanticType:'DISPLAY_ONLY',semanticCategories:[{label:'虹：設定6',semanticType:'EXACT_CONSTRAINT'},{label:'制服：高設定示唆（強）',semanticType:'PROBABILITY_UNKNOWN'}],details:['虹：設定6','制服：高設定示唆（強）']}]};const p:any={...base,settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2','SET_3','SET_4','SET_5','SET_6']},evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);assert.equal(d.package.evidence.evidences.length,1);assert.deepEqual(d.package.evidence.evidences[0].confirmedSettings,['SET_6']);const s=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_mix');assert.match(s.description,/設定候補の絞り込み/);assert.match(s.description,/直接反映していません/)});

test('maps total-game and target-game trial universes to game denominators',()=>{
 const total:any={...base,activeFeatures:[{findingId:'total',name:'小役合算',model:'BERNOULLI',trialUniverse:'TOTAL_GAME_TRIAL',settingDistribution:{'1':'1/10','2':'1/9'},runtimePolicyBinding:{metric:'SELECTION_SCORE',value:8},score:{status:'COMPUTED',value:8}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_total',sourceFindingId:'total',title:'小役合算',inputs:[{id:'total.trials',label:'観測機会数',role:'trial'},{id:'total.hits',label:'該当回数',role:'success'}]}]}};
 const d1=buildAppRuntime(total,ref);const t1=d1.package.ui.v8Sections[0].items[0].inputs[0];assert.equal(t1.label,'総ゲーム数');assert.equal(t1.playDataBinding.source,'PLAY_TOTAL_GAME_DELTA');assert.equal(d1.package.inputs.inputs[0].unit,'G');
 const target:any={...base,activeFeatures:[{findingId:'target',name:'REG後50G間の無限AT移行',model:'BERNOULLI',trialUniverse:'REG_AFTER_50G_GAME_TRIAL',settingDistribution:{'1':'1/100','2':'1/80'},runtimePolicyBinding:{metric:'SELECTION_SCORE',value:8},score:{status:'COMPUTED',value:8}}],runtimeUi:{...base.runtimeUi,numericSections:[{id:'OBS_target',sourceFindingId:'target',title:'REG後50G間の無限AT移行',inputs:[{id:'target.trials',label:'観測機会数',role:'trial'},{id:'target.hits',label:'該当回数',role:'success'}]}]}};
 const d2=buildAppRuntime(target,ref);const t2=d2.package.ui.v8Sections[0].items[0].inputs[0];assert.equal(t2.label,'対象ゲーム数');assert.equal(d2.package.inputs.inputs[0].unit,'G');assert.match(d2.package.ui.v8Sections[0].description,/対象区間で実際に消化したゲーム数/);
});
test('shows evidence object name next to its user-facing meaning',()=>{
 const ev:any={id:'EVI_screen',sourceFindingId:'screen',title:'AT終了画面',runtimePolicyControlled:false,evidenceItems:[{findingId:'screen',label:'AT終了画面',semanticType:'DISPLAY_ONLY',semanticCategories:[{label:'カレン：偶数設定示唆',semanticType:'PROBABILITY_UNKNOWN'},{label:'亡国のアキト：設定6',semanticType:'EXACT_CONSTRAINT'}],details:['カレン：偶数設定示唆','亡国のアキト：設定6']}]};
 const p:any={...base,settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2','SET_3','SET_4','SET_5','SET_6']},evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};
 const d=buildAppRuntime(p,ref);const cats=d.package.ui.v8Sections.find((x:any)=>x.id==='EVI_screen').items[0].interaction.categories;assert.deepEqual(cats.map((x:any)=>[x.label,x.meaning]),[['カレン','偶数設定示唆'],['亡国のアキト','設定6']]);
});

test('materializes exact parity constraints',()=>{const ev:any={id:'EVI_parity',sourceFindingId:'parity',title:'獲得枚数表示',runtimePolicyControlled:false,evidenceItems:[{findingId:'parity',label:'獲得枚数表示',semanticType:'EXACT_CONSTRAINT',semanticCategories:[{label:'246枚：偶数設定濃厚',semanticType:'EXACT_CONSTRAINT'},{label:'135枚：奇数設定濃厚',semanticType:'EXACT_CONSTRAINT'}],details:['246枚：偶数設定濃厚','135枚：奇数設定濃厚']}]};const p:any={...base,settings:{status:'SOURCE_DERIVED',values:['SET_1','SET_2','SET_3','SET_4','SET_5','SET_6']},evidence:[ev],runtimeUi:{...base.runtimeUi,evidenceSections:[ev]}};const d=buildAppRuntime(p,ref);assert.deepEqual(d.package.evidence.evidences[0].confirmedSettings,['SET_2','SET_4','SET_6']);assert.deepEqual(d.package.evidence.evidences[1].confirmedSettings,['SET_1','SET_3','SET_5']);assert.doesNotThrow(()=>validateAppRuntimeDocument(d,p,ref))});
