import test from 'node:test';import assert from 'node:assert/strict';import {buildCanonicalUi} from '../src/canonical-ui-builder.ts';import {validateCanonicalUiDocument} from '../src/canonical-ui-validator.ts';
const candidate={manifestVersion:'8.5',batchId:'b',machineId:'M',machineName:'Machine',dependencyGroups:[{groupId:'held-group',members:['h1'],resolution:'HELD_NO_JOINT_MODEL',reason:'source-supported joint/dependency modelが未確立',reevaluationCondition:'source-supported joint/dependency modelまたは明示的なSelection REVIEW決定が確立すること。'}],candidates:[{findingId:'b1',label:'初当り',model:'BERNOULLI',trialUniverse:'NORMAL',runtimeInferenceAllowed:true,settingDistribution:{'1':'1/100','6':'1/80'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:2,thresholdSource:'RUNTIME_POLICY'}},{findingId:'c1',label:'振り分け',model:'CATEGORICAL',trialUniverse:'END',runtimeInferenceAllowed:true,settingDistribution:{'1':'A 60% / B 40%','6':'A 40% / B 60%'},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:8,thresholdSource:'RUNTIME_POLICY'}},{findingId:'h1',label:'保留',model:'BERNOULLI',trialUniverse:'X',runtimeInferenceAllowed:false,settingDistribution:{'1':0.1,'6':0.2},runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:1,thresholdSource:'RUNTIME_POLICY'}}]};
const observation={machineId:'M',observations:[{findingId:'b1',label:'初当り',model:'BERNOULLI',trialUniverse:'NORMAL',runtimeInferenceAllowed:true,observationStatus:'READY',collectionContract:{type:'SUCCESS_TRIAL_COUNTS',successField:'successCount',trialField:'eligibleTrialCount'}},{findingId:'c1',label:'振り分け',model:'CATEGORICAL',trialUniverse:'END',runtimeInferenceAllowed:true,observationStatus:'READY',collectionContract:{type:'CATEGORY_COUNTS',countsField:'categoryCounts',trialField:'eligibleTrialCount',categoryCoverage:'NON_EXHAUSTIVE'}},{findingId:'h1',label:'保留',model:'BERNOULLI',trialUniverse:'X',runtimeInferenceAllowed:false,observationStatus:'HELD_NO_JOINT_MODEL',collectionContract:null}],evidence:[{findingId:'e1',label:'終了画面',sourceIds:['s'],runtimePolicyControlled:false,status:'SOURCE_REFERENCED'}],highLowDiscrimination:{status:'NOT_COMPUTED',reason:'no exact exposure'}};
const evaluation={machineId:'M',evaluations:[{findingId:'b1',metrics:{selectionScore:{status:'BLOCKED_UNRESOLVED',value:null}},benchmarkExposure:{reason:'exact exposureなし'}},{findingId:'c1',metrics:{selectionScore:{status:'BLOCKED_UNRESOLVED',value:null}},benchmarkExposure:{reason:'exact exposureなし'}},{findingId:'h1',metrics:{selectionScore:{status:'BLOCKED_UNRESOLVED',value:null}},benchmarkExposure:{reason:'exact exposureなし'}}]};const ca={path:'c'},oa={path:'o'},ea={path:'e'};
test('materializes only READY numeric observations and preserves Evidence',()=>{const d=buildCanonicalUi(candidate,observation,evaluation,ca,oa,ea);const ev=validateCanonicalUiDocument(d,candidate,observation,evaluation,ca,oa,ea);assert.equal(d.numericSections.length,2);assert.equal(d.heldObservations[0].materialized,false);assert.match(d.heldObservations[0].reason,/joint\/dependency model/);assert.match(d.heldObservations[0].reevaluationCondition,/Selection REVIEW/);assert.equal(d.evidenceSections[0].runtimePolicyControlled,false);assert.equal(d.numericSections[0].score.display,'算出不可');assert.deepEqual(d.numericSections[0].inputs.map((x:any)=>x.id),['b1.eligibleTrialCount','b1.successCount']);assert.equal(ev[0].validator,'canonical-ui-v1')});
test('rejects Evidence omission',()=>{const d=buildCanonicalUi(candidate,observation,evaluation,ca,oa,ea);d.evidenceSections=[];assert.throws(()=>validateCanonicalUiDocument(d,candidate,observation,evaluation,ca,oa,ea),/EVIDENCE_COVERAGE/)});
test('rejects HELD observation materialization',()=>{const d=buildCanonicalUi(candidate,observation,evaluation,ca,oa,ea);d.numericSections.push({sourceFindingId:'h1',title:'保留',kind:'NUMERIC_OBSERVATION',inputs:[{}]});assert.throws(()=>validateCanonicalUiDocument(d,candidate,observation,evaluation,ca,oa,ea),/NUMERIC_COVERAGE/)});

test('materializes source-explicit residual category',()=>{const c=structuredClone(candidate),e=structuredClone(evaluation);c.candidates[1].settingDistribution={'1':'A 10% / B 20%','6':'A 20% / B 30%'};e.evaluations[1].categoryModel={residualPolicy:'SOURCE_EXPLICIT_OTHER'};const d=buildCanonicalUi(c,observation,e,ca,oa,ea);assert.deepEqual(d.numericSections[1].inputs.map((x:any)=>x.label),['観測機会数','A','B','その他']);assert.doesNotThrow(()=>validateCanonicalUiDocument(d,c,observation,e,ca,oa,ea))});

test('normalizes internal benchmark wording before user UI',()=>{const d=buildCanonicalUi(candidate,observation,evaluation,ca,oa,ea);for(const section of d.numericSections){assert.doesNotMatch(String(section.score?.reason??''),/opportunity model|research|exact exposure|denominator/i);assert.match(String(section.score?.reason??''),/観測条件/);}});
