import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {RepoStore,Orchestrator,MockWorkerAdapter,dispatchable,schedule,renewLease} from '../src/core.ts';import type {Stage} from '../src/core.ts';
const setup=(now=new Date('2026-09-28T00:00:00Z'))=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'orch-'));const s=new RepoStore(root);const o=new Orchestrator(s,()=>now);const x:Stage={batchId:'bat_test',machineId:'M1',name:'RESEARCH',state:'READY',revision:0,dependencies:[],authoritativeInputFingerprint:'fp1',contractVersion:'c1'};o.saveStage(x);return {root,s,o,x,worker:new MockWorkerAdapter()}};
test('happy path + duplicate no-op + restart persistence',()=>{const {root,o,x,worker}=setup();const a=o.createAttempt(x),l=o.acquire(x,a);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','DISPATCH',a.workId);st=o.transition(st,'RUNNING','WORKER_START',a.workId);const r=worker.execute(o.request(st,a,l));assert.equal(o.accept(r).kind,'COMMITTED');assert.equal(o.accept(r).kind,'DUPLICATE');const o2=new Orchestrator(new RepoStore(root),()=>new Date('2026-09-28T00:00:00Z'));assert.equal(o2.stage('bat_test','M1','RESEARCH').state,'COMPLETE')});
test('expired lease old SUCCESS is stale',()=>{let now=new Date('2026-09-28T00:00:00Z');const {o,x,worker}=setup(now);o.now=()=>now;const a=o.createAttempt(x),l=o.acquire(x,a,10);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','D',a.workId);st=o.transition(st,'RUNNING','S',a.workId);const r=worker.execute(o.request(st,a,l));now=new Date(now.getTime()+20);o.expire(l);assert.equal(o.accept(r).kind,'STALE');assert.equal(o.stage('bat_test','M1','RESEARCH').state,'RUNNING')});
test('single writer invariant',()=>{const {o,x}=setup();o.acquire(x,o.createAttempt(x));assert.throws(()=>o.acquire(x,o.createAttempt(x)),/ACTIVE_WRITER_EXISTS/)});
test('retry creates immutable new attempt',()=>{const {o,x,worker}=setup();const a=o.createAttempt(x),l=o.acquire(x,a);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','D',a.workId);st=o.transition(st,'RUNNING','S',a.workId);assert.equal(o.accept(worker.execute(o.request(st,a,l),'FAILED_RETRYABLE')).kind,'RETRY_WAIT');st=o.reconcile('bat_test','M1','RESEARCH');const a2=o.createAttempt(st);assert.equal(a2.number,2);assert.notEqual(a2.attemptId,a.attemptId)});
test('WAIT_EXTERNAL and HUMAN_REQUIRED recover',()=>{for(const status of ['WAIT_EXTERNAL','HUMAN_REQUIRED'] as const){const {o,x,worker}=setup();const a=o.createAttempt(x),l=o.acquire(x,a);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','D',a.workId);st=o.transition(st,'RUNNING','S',a.workId);o.accept(worker.execute(o.request(st,a,l),status));st=o.stage('bat_test','M1','RESEARCH');if(status==='WAIT_EXTERNAL')st.externalResolved=true;else st.humanResolved=true;o.saveStage(st);assert.equal(o.reconcile('bat_test','M1','RESEARCH').state,'READY')}});
test('input change makes result stale',()=>{const {o,x,worker}=setup();const a=o.createAttempt(x),l=o.acquire(x,a);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','D',a.workId);st=o.transition(st,'RUNNING','S',a.workId);const r=worker.execute(o.request(st,a,l));st.authoritativeInputFingerprint='fp2';o.saveStage(st);assert.equal(o.accept(r).kind,'STALE')});
test('CAS and illegal transitions rejected',()=>{const {o,x}=setup();assert.throws(()=>o.transition(x,'COMPLETE','bad','bad'),/ILLEGAL/);const cur=o.stage('bat_test','M1','RESEARCH');cur.revision=1;assert.throws(()=>o.transition(cur,'LEASED','x','x',0),/CAS_CONFLICT/)});
test('machine isolation',()=>{const {o,x,worker}=setup();o.saveStage({...x,machineId:'M2'});const a=o.createAttempt(x),l=o.acquire(x,a);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','D',a.workId);st=o.transition(st,'RUNNING','S',a.workId);o.accept(worker.execute(o.request(st,a,l),'FAILED_TERMINAL'));assert.equal(o.stage('bat_test','M1','RESEARCH').state,'FAILED');assert.equal(o.stage('bat_test','M2','RESEARCH').state,'READY')});
test('dispatchable dependencies + scheduler slot',()=>{const {x}=setup();const dep={...x,name:'DEP',state:'COMPLETE' as const};const y={...x,dependencies:['DEP']};assert.equal(dispatchable(y,{DEP:dep},new Date()),true);assert.equal(schedule([y,{...y,machineId:'M2'}],{DEP:dep},1,new Date()).length,1)});
test('lease renewal active only',()=>{let now=new Date('2026-09-28T00:00:00Z');const {s,o,x}=setup(now);const a=o.createAttempt(x),l=o.acquire(x,a,100);now=new Date(now.getTime()+50);assert.ok(Date.parse(renewLease(s,l,now,100).expiresAt)>now.getTime());l.status='RELEASED';assert.throws(()=>renewLease(s,l,now),/LEASE_NOT_RENEWABLE/)});

test('schema guards reject malformed state/result',()=>{const {o}=setup();assert.throws(()=>o.saveStage({} as any),/SCHEMA_INVALID_STAGE/);assert.throws(()=>o.accept({} as any),/SCHEMA_INVALID_WORK_RESULT/)});
test('compare-and-commit rejects TOCTOU mutation after validation',()=>{const {o,x,worker}=setup();const a=o.createAttempt(x),l=o.acquire(x,a);let st=o.transition(o.stage('bat_test','M1','RESEARCH'),'LEASED','D',a.workId);st=o.transition(st,'RUNNING','S',a.workId);const r=worker.execute(o.request(st,a,l));const original=o.validate.bind(o);o.validate=(z)=>{const ok=original(z);const changed=o.stage('bat_test','M1','RESEARCH');changed.authoritativeInputFingerprint='changed-during-validation';o.saveStage(changed);return ok};assert.equal(o.accept(r).kind,'STALE');assert.equal(o.stage('bat_test','M1','RESEARCH').state,'VALIDATING')});
