import test from 'node:test';import assert from 'node:assert/strict';import {buildDependencyReview} from '../src/dependency-gate.ts';
test('same denominator alone does not create a dependency group',()=>{const d=buildDependencyReview([{findingId:'a',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.1,'6':0.2}},{findingId:'b',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.05,'6':0.1}}]);assert.equal(d.summary.candidateCount,2);assert.equal(d.summary.groupCount,0);assert.equal(d.decisions.get('a').status,'NONE');assert.equal(d.decisions.get('b').status,'NONE')});
test('explicit independent review is respected',()=>{const d=buildDependencyReview([{findingId:'a',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.1,'6':0.2},dependencyReview:{status:'INDEPENDENT',reason:'別抽選で直接的な包含関係がないことを確認。'}},{findingId:'b',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.05,'6':0.1}}]);assert.equal(d.decisions.get('a').kind,'INDEPENDENT');assert.equal(d.decisions.get('b').kind,'REVIEWED_NO_OVERLAP')});
test('explicit cross-universe causal group is preserved',()=>{const d=buildDependencyReview([{findingId:'all',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.1,'6':0.2},dependencyGroupId:'g',dependencyKind:'CAUSAL_OVERLAP',dependencyReason:'全体値'},{findingId:'part',observationType:'conditional_probability',trialUniverse:'ROLE_TRIAL',settingDistribution:{'1':0.05,'6':0.1},dependencyGroupId:'g',dependencyKind:'CAUSAL_OVERLAP',dependencyReason:'全体の一部'}]);assert.equal(d.decisions.get('all').groupId,'g');assert.equal(d.decisions.get('part').groupId,'g')});

test('cross-universe subset names alone do not prove dependency',()=>{const d=buildDependencyReview([{findingId:'all',observationType:'conditional_probability',trialUniverse:'SUIKA_TRIAL',settingDistribution:{'1':0.03,'6':0.04}},{findingId:'lock',observationType:'conditional_probability',trialUniverse:'SUIKA_REEL_LOCK_TRIAL',settingDistribution:{'1':0.51,'6':0.58}}]);assert.equal(d.summary.groupCount,0);assert.equal(d.decisions.get('all').kind,'REVIEWED_NO_OVERLAP');assert.equal(d.decisions.get('lock').kind,'REVIEWED_NO_OVERLAP')});


test('shared denominator is explicitly non-exclusive',()=>{const d=buildDependencyReview([{findingId:'bell',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.01,'6':0.02},dependencyReview:{status:'SHARED_DENOMINATOR',reason:'同じ通常ゲーム数を分母にするだけ。'}},{findingId:'hit',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.003,'6':0.004},dependencyReview:{status:'SHARED_DENOMINATOR',reason:'同じ通常ゲーム数を分母にするだけ。'}}]);assert.equal(d.summary.groupCount,0);assert.equal(d.decisions.get('bell').kind,'SHARED_DENOMINATOR');assert.equal(d.decisions.get('hit').kind,'SHARED_DENOMINATOR')});
test('nested and causal path metadata create one explicit family',()=>{const d=buildDependencyReview([{findingId:'initial',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.1,'6':0.2},dependencyGroupId:'path',dependencyKind:'NESTED_OUTCOME',dependencyReason:'同じ当選の流れを一部共有する。'},{findingId:'rush',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.05,'6':0.1},dependencyGroupId:'path',dependencyKind:'NESTED_OUTCOME',dependencyReason:'最終結果。'},{findingId:'cz',observationType:'probability',trialUniverse:'NORMAL_GAME_TRIAL',settingDistribution:{'1':0.01,'6':0.02},dependencyGroupId:'path',dependencyKind:'CAUSAL_PATH_OVERLAP',dependencyReason:'途中経路。'}]);assert.equal(d.summary.groupCount,1);assert.deepEqual(new Set(d.summary.groups[0].kinds),new Set(['NESTED_OUTCOME','CAUSAL_PATH_OVERLAP']))});
