import test from 'node:test';import assert from 'node:assert/strict';import {buildMachineData} from '../src/machine-data-builder.ts';import {validateMachineDataDocument} from '../src/machine-data-validator.ts';
const candidate={batchId:'b',machineId:'M',machineName:'Machine',candidates:[{findingId:'ready',label:'Ready',model:'BERNOULLI',trialUniverse:'T',settingDistribution:{'1':'1/100','6':'1/80'},runtimeInferenceAllowed:true,runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:2,thresholdSource:'RUNTIME_POLICY'}},{findingId:'held',label:'Held',model:'BERNOULLI',trialUniverse:'T',settingDistribution:{'1':'1/200','6':'1/150'},runtimeInferenceAllowed:false,runtimePolicyBinding:{metric:'PER_ELIGIBLE_TRIAL_POWER',value:1,thresholdSource:'RUNTIME_POLICY'}}]};
const ui={batchId:'b',machineId:'M',machineName:'Machine',numericSections:[{sourceFindingId:'ready',title:'Ready',score:{label:'設定判別スコア',status:'NOT_COMPUTED',display:'算出不可',reason:'x'},perEligibleTrialPower:{label:'1回の判別力',value:2,metric:'PER_ELIGIBLE_TRIAL_POWER',thresholdSource:'RUNTIME_POLICY'},inputs:[{id:'trial'},{id:'success'}]}],evidenceSections:[{sourceFindingId:'e',title:'Evidence',runtimePolicyControlled:false,evidenceItems:[{findingId:'e'}]}],heldObservations:[{findingId:'held',materialized:false}],machineInferenceSummary:{highLowDiscrimination:{status:'NOT_COMPUTED',reason:'x'}}};
const observation={machineId:'M',blockedItems:[{blockId:'b1'}],sourceReferences:[{sourceId:'s1'}]};const ur={path:'u'},cr={path:'c'},or={path:'o'};
test('builds runtime-ready package from canonical sources only',()=>{const d=buildMachineData(ui,candidate,observation,ur,cr,or);const v=validateMachineDataDocument(d,ui,candidate,observation,ur,cr,or);assert.equal(d.features.length,1);assert.deepEqual(d.settings.values,['SET_1','SET_6']);assert.equal(d.evidence[0].runtimePolicyControlled,false);assert.equal(v[0].validator,'machine-data-v1')});
test('rejects held feature materialization',()=>{const d=buildMachineData(ui,candidate,observation,ur,cr,or);d.features.push({findingId:'held'});assert.throws(()=>validateMachineDataDocument(d,ui,candidate,observation,ur,cr,or),/FEATURE_COVERAGE|HELD_MATERIALIZED/)});
test('rejects evidence mutation',()=>{const d=buildMachineData(ui,candidate,observation,ur,cr,or);d.evidence[0].runtimePolicyControlled=true;assert.throws(()=>validateMachineDataDocument(d,ui,candidate,observation,ur,cr,or),/EVIDENCE_COPY|EVIDENCE_RUNTIME_POLICY/)});

test('falls back to research distributions for machine setting keys',()=>{const r={machineId:'M',findings:[{settingDistribution:{'1':'x','2':'x','4':'x','5':'x','6':'x'}}]};const d=buildMachineData({...ui,numericSections:[],heldObservations:[]},{...candidate,candidates:[]},observation,ur,cr,or,r,{path:'r'});assert.deepEqual(d.settings.values,['SET_1','SET_2','SET_4','SET_5','SET_6']);assert.doesNotThrow(()=>validateMachineDataDocument(d,{...ui,numericSections:[],heldObservations:[]},{...candidate,candidates:[]},observation,ur,cr,or,r,{path:'r'}))});
