import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {RepoStore,Orchestrator,MockWorkerAdapter} from '../src/core.ts';import {PRODUCTION_STAGES,STAGE_WORKER,initializeBatch,promoteDependencies,dashboard,reconcileBatch,scheduleByKind,appendProvenance,productionRequest,acceptAndRecord} from '../src/runtime.ts';
const setup=()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p15-'));const s=new RepoStore(root);initializeBatch(s,{batchId:'bat_dry',manifestVersion:'8.5',waves:[{waveId:'w1',machineIds:['M1','M2','M3','M4','M5']},{waveId:'w2',machineIds:['M6','M7','M8','M9','M10']}]});return {s,o:new Orchestrator(s,()=>new Date('2026-09-28T06:00:00Z'))}};
test('creates 5-machine x2 waves and full production stage graph',()=>{const {s,o}=setup();assert.equal(PRODUCTION_STAGES.length,12);assert.equal(fs.readdirSync(s.p('batches','bat_dry','machines')).length,10);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'READY');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'PENDING');assert.equal(STAGE_WORKER.DEVICE_QA,'HUMAN')});
test('dependency completion promotes only next stage',()=>{const {o}=setup();let x=o.stage('bat_dry','M1','RESEARCH');x=o.transition(x,'LEASED','D','1');x=o.transition(x,'RUNNING','S','1');x=o.transition(x,'VALIDATING','V','1');o.transition(x,'COMPLETE','C','1');promoteDependencies(o,'bat_dry','M1');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'READY');assert.equal(o.stage('bat_dry','M1','ELIGIBILITY').state,'PENDING')});
test('slot scheduler isolates kinds and caps concurrency',()=>{const {s,o}=setup();assert.equal(scheduleByKind(o,s,'bat_dry',{semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1},'SEMANTIC').length,2);assert.equal(scheduleByKind(o,s,'bat_dry',{semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1},'PRODUCTION').length,0)});
test('dashboard projects machine state without becoming authority',()=>{const {s}=setup();const d=dashboard(s,'bat_dry');assert.equal(d.machines.length,10);assert.equal(d.counts.READY,10)});
test('reconcile is restart-safe and promotes resolved waits',()=>{const {s,o}=setup();let x=o.stage('bat_dry','M1','RESEARCH');x=o.transition(x,'LEASED','D','1');x=o.transition(x,'RUNNING','S','1');x.activeAttemptId=undefined;x.activeLeaseId=undefined;x=o.transition(x,'WAIT_EXTERNAL','W','1');x.externalResolved=true;o.saveStage(x);const o2=new Orchestrator(new RepoStore(s.root),()=>new Date('2026-09-28T06:00:00Z'));const d=reconcileBatch(o2,new RepoStore(s.root),'bat_dry');assert.equal(o2.stage('bat_dry','M1','RESEARCH').state,'READY');assert.equal(d.machines.length,10)});
test('artifact provenance is append-only repository evidence',()=>{const {s}=setup();appendProvenance(s,'bat_dry',{workId:'w',attemptId:'a',machineId:'M1',stage:'RESEARCH',inputArtifacts:[],outputArtifacts:[{artifactId:'x',kind:'research',path:'production/batches/bat_dry/artifacts/x.json',sha256:'abc',producerWorkId:'w'}],workerAdapter:'semantic-mock',validatorAdapter:'deterministic',recordedAt:'2026-09-28T06:00:00Z'});const p=fs.readFileSync(s.p('batches','bat_dry','provenance','chain.jsonl'),'utf8').trim().split('\n');assert.equal(p.length,1);assert.equal(JSON.parse(p[0]).workId,'w')});
test('dry-run one semantic WorkRequest lifecycle keeps orchestrator authority',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','DISPATCH',a.workId);x=o.transition(x,'RUNNING','WORKER_START',a.workId);const q=o.request(x,a,l);q.workerType='SEMANTIC';const r=worker.execute(q);assert.equal(o.accept(r).kind,'COMMITTED');promoteDependencies(o,'bat_dry','M1');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'READY')});

test('rejects malformed wave/batch shape and duplicate machine ids',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p15-invalid-'));const s=new RepoStore(root);assert.throws(()=>initializeBatch(s,{batchId:'bad',manifestVersion:'8.5',waves:[{waveId:'w1',machineIds:['M1','M2','M3','M4','M5']},{waveId:'w2',machineIds:['M5','M6','M7','M8','M9']}]}),/INVALID_BATCH_SHAPE/)});
test('WAIT_EXTERNAL recovery releases writer and permits a new immutable attempt',()=>{const {o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);assert.equal(o.accept(worker.execute(o.request(x,a,l),'WAIT_EXTERNAL')).kind,'WAIT_EXTERNAL');x=o.stage('bat_dry','M1','RESEARCH');x.externalResolved=true;o.saveStage(x);x=o.reconcile('bat_dry','M1','RESEARCH');const a2=o.createAttempt(x);assert.doesNotThrow(()=>o.acquire(x,a2));assert.notEqual(a2.attemptId,a.attemptId)});
test('one machine terminal failure does not block other machines in batch scheduler',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);o.accept(worker.execute(o.request(x,a,l),'FAILED_TERMINAL'));const next=scheduleByKind(o,s,'bat_dry',{semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1},'SEMANTIC');assert.equal(next.length,2);assert.ok(next.every(z=>z.machineId!=='M1'))});

test('production request declares stage artifact contract and committed result records provenance',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);const q=productionRequest(o,x,a,l);assert.equal(q.workerType,'SEMANTIC');assert.equal(q.expectedOutputs[0].kind,'research');const r=worker.execute(q);r.producedArtifacts=[{artifactId:'r1',kind:'research',path:'production/batches/bat_dry/artifacts/M1/research/result.json',sha256:'abc',producerWorkId:r.workId}];assert.equal(acceptAndRecord(o,s,r,'semantic-mock','deterministic').kind,'COMMITTED');const p=fs.readFileSync(s.p('batches','bat_dry','provenance','chain.jsonl'),'utf8').trim();assert.equal(JSON.parse(p).outputArtifacts[0].artifactId,'r1')});
