import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {RepoStore,Orchestrator,MockWorkerAdapter} from '../src/core.ts';import {PRODUCTION_STAGES,STAGE_WORKER,initializeBatch,promoteDependencies,dashboard,reconcileBatch,scheduleByKind,activeResearchWave,appendProvenance,productionRequest,acceptAndRecord} from '../src/runtime.ts';

const researchArtifact=(s:RepoStore,b:string,m:string,w:string)=>{const rel=`batches/${b}/artifacts/${m}/research/result.json`;const full=s.p(rel);fs.mkdirSync(path.dirname(full),{recursive:true});const d={schemaVersion:'research-v1',manifestVersion:'8.5',batchId:b,machineId:m,machineName:'Test Machine',workId:w,sources:[{sourceId:'s1',url:'https://example.com/source',title:'Source',sourceType:'official',claims:['claim']}],findings:[{findingId:'f1',label:'rate',observationType:'probability',sourceIds:['s1'],settingDistribution:{'1':0.1,'6':0.2}}],blockedItems:[{blockId:'b1',label:'unknown',reason:'not published',reevaluationCondition:'setting-specific distribution is published'}]};const bytes=Buffer.from(JSON.stringify(d,null,2));fs.writeFileSync(full,bytes);return {artifactId:'research-result',kind:'research',path:`production/${rel}`,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),producerWorkId:w}}
const setup=()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p15-'));const s=new RepoStore(root);initializeBatch(s,{batchId:'bat_dry',manifestVersion:'8.5',waves:[{waveId:'w1',machineIds:['M1','M2','M3','M4','M5']},{waveId:'w2',machineIds:['M6','M7','M8','M9','M10']}]});return {s,o:new Orchestrator(s,()=>new Date('2026-09-28T06:00:00Z'))}};
test('creates 5-machine x2 waves and full production stage graph',()=>{const {s,o}=setup();assert.equal(PRODUCTION_STAGES.length,12);assert.equal(fs.readdirSync(s.p('batches','bat_dry','machines')).length,10);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'READY');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'PENDING');assert.equal(STAGE_WORKER.DEVICE_QA,'HUMAN')});
test('dependency completion promotes only next stage',()=>{const {o}=setup();let x=o.stage('bat_dry','M1','RESEARCH');x=o.transition(x,'LEASED','D','1');x=o.transition(x,'RUNNING','S','1');x=o.transition(x,'VALIDATING','V','1');o.transition(x,'COMPLETE','C','1');promoteDependencies(o,'bat_dry','M1');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'READY');assert.equal(o.stage('bat_dry','M1','ELIGIBILITY').state,'PENDING')});
test('slot scheduler isolates kinds and caps concurrency',()=>{const {s,o}=setup();assert.equal(scheduleByKind(o,s,'bat_dry',{semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1},'SEMANTIC').length,2);assert.equal(scheduleByKind(o,s,'bat_dry',{semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1},'PRODUCTION').length,0)});
test('RESEARCH dispatch is gated to one 5-machine wave at a time',()=>{const {s,o}=setup();const slots={semanticSlots:10,productionSlots:2,validationSlots:2,integrationSlots:1};assert.equal(activeResearchWave(s,'bat_dry'),'w1');let q=scheduleByKind(o,s,'bat_dry',slots,'SEMANTIC');assert.deepEqual(q.filter(x=>x.name==='RESEARCH').map(x=>x.machineId),['M1','M2','M3','M4','M5']);for(const m of ['M1','M2','M3','M4','M5']){let x=o.stage('bat_dry',m,'RESEARCH');x=o.transition(x,'LEASED','D','1');x=o.transition(x,'RUNNING','S','1');x=o.transition(x,'VALIDATING','V','1');o.transition(x,'COMPLETE','C','1')}assert.equal(activeResearchWave(s,'bat_dry'),'w2');q=scheduleByKind(o,s,'bat_dry',slots,'SEMANTIC');assert.deepEqual(q.filter(x=>x.name==='RESEARCH').map(x=>x.machineId),['M10','M6','M7','M8','M9'])});
test('dashboard projects machine state without becoming authority',()=>{const {s}=setup();const d=dashboard(s,'bat_dry');assert.equal(d.machines.length,10);assert.equal(d.counts.READY,10)});
test('reconcile is restart-safe and promotes resolved waits',()=>{const {s,o}=setup();let x=o.stage('bat_dry','M1','RESEARCH');x=o.transition(x,'LEASED','D','1');x=o.transition(x,'RUNNING','S','1');x.activeAttemptId=undefined;x.activeLeaseId=undefined;x=o.transition(x,'WAIT_EXTERNAL','W','1');x.externalResolved=true;o.saveStage(x);const o2=new Orchestrator(new RepoStore(s.root),()=>new Date('2026-09-28T06:00:00Z'));const d=reconcileBatch(o2,new RepoStore(s.root),'bat_dry');assert.equal(o2.stage('bat_dry','M1','RESEARCH').state,'READY');assert.equal(d.machines.length,10)});
test('artifact provenance is append-only repository evidence',()=>{const {s}=setup();appendProvenance(s,'bat_dry',{workId:'w',attemptId:'a',machineId:'M1',stage:'RESEARCH',inputArtifacts:[],outputArtifacts:[{artifactId:'x',kind:'research',path:'production/batches/bat_dry/artifacts/x.json',sha256:'abc',producerWorkId:'w'}],workerAdapter:'semantic-mock',validatorAdapter:'deterministic',recordedAt:'2026-09-28T06:00:00Z'});const p=fs.readFileSync(s.p('batches','bat_dry','provenance','chain.jsonl'),'utf8').trim().split('\n');assert.equal(p.length,1);assert.equal(JSON.parse(p[0]).workId,'w')});
test('dry-run one semantic WorkRequest lifecycle keeps orchestrator authority',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','DISPATCH',a.workId);x=o.transition(x,'RUNNING','WORKER_START',a.workId);const q=o.request(x,a,l);q.workerType='SEMANTIC';const r=worker.execute(q);assert.equal(o.accept(r).kind,'COMMITTED');promoteDependencies(o,'bat_dry','M1');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'READY')});

test('rejects malformed wave/batch shape and duplicate machine ids',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p15-invalid-'));const s=new RepoStore(root);assert.throws(()=>initializeBatch(s,{batchId:'bad',manifestVersion:'8.5',waves:[{waveId:'w1',machineIds:['M1','M2','M3','M4','M5']},{waveId:'w2',machineIds:['M5','M6','M7','M8','M9']}]}),/INVALID_BATCH_SHAPE/)});
test('WAIT_EXTERNAL recovery releases writer and permits a new immutable attempt',()=>{const {o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);assert.equal(o.accept(worker.execute(o.request(x,a,l),'WAIT_EXTERNAL')).kind,'WAIT_EXTERNAL');x=o.stage('bat_dry','M1','RESEARCH');x.externalResolved=true;o.saveStage(x);x=o.reconcile('bat_dry','M1','RESEARCH');const a2=o.createAttempt(x);assert.doesNotThrow(()=>o.acquire(x,a2));assert.notEqual(a2.attemptId,a.attemptId)});
test('one machine terminal failure does not block other machines in batch scheduler',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);o.accept(worker.execute(o.request(x,a,l),'FAILED_TERMINAL'));const next=scheduleByKind(o,s,'bat_dry',{semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1},'SEMANTIC');assert.equal(next.length,2);assert.ok(next.every(z=>z.machineId!=='M1'))});

test('production request declares stage artifact contract and committed result records provenance',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);const q=productionRequest(o,x,a,l);assert.equal(q.workerType,'SEMANTIC');assert.equal(q.expectedOutputs[0].kind,'research');const r=worker.execute(q);r.producedArtifacts=[researchArtifact(s,'bat_dry','M1',r.workId)];assert.equal(acceptAndRecord(o,s,r,'semantic-mock','deterministic').kind,'COMMITTED');const p=fs.readFileSync(s.p('batches','bat_dry','provenance','chain.jsonl'),'utf8').trim();assert.equal(JSON.parse(p).outputArtifacts[0].artifactId,'research-result')});

test('artifact contract violation is rejected before authoritative COMPLETE',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);const r=worker.execute(productionRequest(o,x,a,l));r.producedArtifacts=[{artifactId:'bad',kind:'wrong',path:'production/batches/bat_dry/artifacts/M1/research/bad.json',sha256:'abc',producerWorkId:r.workId}];assert.throws(()=>acceptAndRecord(o,s,r,'semantic-mock','deterministic'),/ARTIFACT_CONTRACT_VIOLATION/);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'RUNNING')});

test('formal dispatch path keeps wave gate and creates authoritative attempt/lease/request',()=>{
 const {s,o}=setup();const c={semanticSlots:2,productionSlots:2,validationSlots:2,integrationSlots:1};
 const selected=scheduleByKind(o,s,'bat_dry',c,'SEMANTIC');
 assert.deepEqual(selected.map(x=>x.machineId),['M1','M2']);
 for(const candidate of selected){
  let x=o.stage('bat_dry',candidate.machineId,candidate.name);
  const a=o.createAttempt(x),l=o.acquire(x,a);
  x=o.transition(o.stage('bat_dry',candidate.machineId,candidate.name),'LEASED','DISPATCH',a.workId);
  x=o.transition(x,'RUNNING','WORKER_START',a.workId);
  const q=productionRequest(o,x,a,l);
  s.write(q,'batches','bat_dry','work-requests',q.workId+'.json');
  assert.equal(q.workerType,'SEMANTIC');assert.equal(q.stage,'RESEARCH');
  assert.equal(o.stage('bat_dry',candidate.machineId,'RESEARCH').state,'RUNNING');
  assert.ok(s.exists('batches','bat_dry','work-requests',q.workId+'.json'));
 }
 assert.equal(o.stage('bat_dry','M3','RESEARCH').state,'READY');
 assert.equal(o.stage('bat_dry','M6','RESEARCH').state,'READY');
 assert.equal(activeResearchWave(s,'bat_dry'),'w1');
});

test('result ingestion contract commits research provenance and promotes only EVALUATION',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','DISPATCH',a.workId);x=o.transition(x,'RUNNING','WORKER_START',a.workId);const q=productionRequest(o,x,a,l);const r=worker.execute(q);r.producedArtifacts=[researchArtifact(s,'bat_dry','M1',r.workId)];const accepted=acceptAndRecord(o,s,r,'semantic-worker','deterministic');assert.equal(accepted.kind,'COMMITTED');if(accepted.kind==='COMMITTED')promoteDependencies(o,accepted.stage.batchId,accepted.stage.machineId);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'COMPLETE');assert.equal(o.stage('bat_dry','M1','EVALUATION').state,'READY');assert.equal(o.stage('bat_dry','M1','ELIGIBILITY').state,'PENDING');const p=fs.readFileSync(s.p('batches','bat_dry','provenance','chain.jsonl'),'utf8').trim();assert.equal(JSON.parse(p).workerAdapter,'semantic-worker')});


test('RESEARCH validator rejects tampered artifact SHA before state transition',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);const r=worker.execute(productionRequest(o,x,a,l));const ref=researchArtifact(s,'bat_dry','M1',r.workId);ref.sha256='0'.repeat(64);r.producedArtifacts=[ref];assert.throws(()=>acceptAndRecord(o,s,r,'semantic-worker','deterministic'),/SHA256_MISMATCH/);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'RUNNING')});

test('RESEARCH validator rejects BLOCK without reevaluation condition',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);const r=worker.execute(productionRequest(o,x,a,l));const ref=researchArtifact(s,'bat_dry','M1',r.workId);const file=s.p(ref.path.slice('production/'.length));const d=JSON.parse(fs.readFileSync(file,'utf8'));d.blockedItems[0].reevaluationCondition='';const bytes=Buffer.from(JSON.stringify(d,null,2)+'\n');fs.writeFileSync(file,bytes);ref.sha256=crypto.createHash('sha256').update(bytes).digest('hex');r.producedArtifacts=[ref];assert.throws(()=>acceptAndRecord(o,s,r,'semantic-worker','deterministic'),/BLOCK_REEVALUATION_REQUIRED/);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'RUNNING')});

test('RESEARCH validator rejects explicitly inferred setting values',()=>{const {s,o}=setup();const worker=new MockWorkerAdapter();let x=o.stage('bat_dry','M1','RESEARCH');const a=o.createAttempt(x),l=o.acquire(x,a);x=o.transition(o.stage('bat_dry','M1','RESEARCH'),'LEASED','D',a.workId);x=o.transition(x,'RUNNING','S',a.workId);const r=worker.execute(productionRequest(o,x,a,l));const ref=researchArtifact(s,'bat_dry','M1',r.workId);const file=s.p(ref.path.slice('production/'.length));const d=JSON.parse(fs.readFileSync(file,'utf8'));d.findings[0].inferred=true;const bytes=Buffer.from(JSON.stringify(d,null,2)+'\n');fs.writeFileSync(file,bytes);ref.sha256=crypto.createHash('sha256').update(bytes).digest('hex');r.producedArtifacts=[ref];assert.throws(()=>acceptAndRecord(o,s,r,'semantic-worker','deterministic'),/INFERRED_VALUE_FORBIDDEN/);assert.equal(o.stage('bat_dry','M1','RESEARCH').state,'RUNNING')});
