import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import {legacyProjection,assertNoDuplicates} from "../tools/lib/evidence-contract-m7.mjs";import {buildMachineData} from "../tools/build-machine-data.mjs";import {compileEvidenceContract} from "../tools/migrate-selection-evidence-contract.mjs";
test("legacy projection preserves IDs, values and unset defaults",()=>{const p=legacyProjection({evidenceUi:{groups:[{groupId:"G",label:"G",selectionMode:"multi",options:[{value:"V",label:"V",allowedSettings:["SET_2"],sourceEvidenceIds:["RE"]}]}]}});assert.equal(p.inputs[0].id,"INP_EVI_G");assert.equal(p.inputs[0].type,"multi_enum");assert.equal(p.items[0].triggerValue,"V");});
test("semantic duplicates fail closed",()=>{const e={evidenceId:"A",sourceResearchEvidenceIds:["RE"],inputId:"I",triggerValue:"V",confirmedSettings:["S"],deniedSettings:[],settingFloorSemantics:"EXACT_ALLOWED_SETTINGS"};assert.throws(()=>assertNoDuplicates([e,{...e,evidenceId:"B"}]),/DUPLICATE_SEMANTIC/);});
test("Hanabi before and after runtime projections are byte-equivalent",()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));const research=read("../research/L_HANABI_KM/research-data.json"),legacy=read("fixtures/evidence-contract-m7/L_HANABI_KM-selection-legacy.json"),migrated=read("../research/L_HANABI_KM/selection-data.json"),stats=read("../research/L_HANABI_KM/statistics-report.json");assert.deepEqual(buildMachineData(research,migrated,stats),buildMachineData(research,legacy,stats));});
test("v2 plus legacy groups cannot materialize simultaneously",()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));const research=read("../research/L_HANABI_KM/research-data.json"),migrated=read("../research/L_HANABI_KM/selection-data.json");migrated.evidenceUi={groups:[{groupId:"DUP",options:[]}]};assert.throws(()=>buildMachineData(research,migrated),/atomic cutover/);});
const migrationFixture=()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));return{selection:read("fixtures/evidence-contract-m7/L_HANABI_KM-selection-legacy.json"),research:read("../research/L_HANABI_KM/research-data.json"),observation:read("../research/L_HANABI_KM/machine-observation-data.json"),ui:read("../research/L_HANABI_KM/ui-design-data.json"),specification:read("../migration-specs/evidence-contract-m7/L_HANABI_KM.json")};};
for(const [name,mutate,pattern] of [
  ["missing normalization proof",x=>delete x.specification.items[0].normalizationSemantics,/normalizationSemantics proof missing/],
  ["missing setting-floor proof",x=>delete x.specification.items[0].settingFloorSemantics,/settingFloorSemantics proof missing/],
  ["ambiguous Observation proof",x=>x.specification.items[0].observationIds.push("OBS_BONUS_OUTCOME"),/Observation mapping is not unique/],
  ["ambiguous canonical UI placement",x=>x.ui.sections.DUPLICATE={inputIds:["INP_EVI_HANABI_REG_END"]},/canonical UI placement is not unique/],
  ["unproven Feature sharing",x=>delete x.specification.items[0].featureSharing,/Feature\/Evidence sharing proof missing/]
])test(name,()=>{const x=migrationFixture();mutate(x);assert.throws(()=>compileEvidenceContract(x),pattern);});

const creaFixture=()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));return{selection:read("fixtures/evidence-contract-m7/LB_CREA_BONUS_TRIGGER_A2-selection-legacy.json"),research:read("../research/LB_CREA_BONUS_TRIGGER_A2/research-data.json"),observation:read("../research/LB_CREA_BONUS_TRIGGER_A2/machine-observation-data.json"),ui:read("../research/LB_CREA_BONUS_TRIGGER_A2/ui-design-data.json"),specification:read("../migration-specs/evidence-contract-m7/LB_CREA_BONUS_TRIGGER_A2.json")};};
test("CREA two-group eight-Evidence migration is byte-equivalent",()=>{const x=creaFixture(),migrated=compileEvidenceContract(x),stats=JSON.parse(fs.readFileSync(new URL("../research/LB_CREA_BONUS_TRIGGER_A2/statistics-report.json",import.meta.url)));assert.equal(x.selection.evidenceUi.groups.length,2);assert.equal(migrated.evidenceContract.inputs.length,2);assert.equal(migrated.evidenceContract.items.length,8);assert.deepEqual(buildMachineData(x.research,migrated,stats),buildMachineData(x.research,x.selection,stats));});
test("CREA groups remain isolated for multi- and cross-group selections",()=>{const items=compileEvidenceContract(creaFixture()).evidenceContract.items,apply=values=>items.filter(e=>(values[e.inputId]??[]).some(v=>String(v)===String(e.triggerValue))).map(e=>e.evidenceId);assert.deepEqual(apply({INP_EVI_CREA_TROPHY:["BRONZE_2PLUS","GOLD_4PLUS"]}),["EVI_CREA_TROPHY_BRONZE_2PLUS","EVI_CREA_TROPHY_GOLD_4PLUS"]);assert.deepEqual(apply({INP_EVI_CREA_TROPHY:["RAINBOW_6"],INP_EVI_CREA_REG_CARD:["RED_4PLUS"]}),["EVI_CREA_TROPHY_RAINBOW_6","EVI_CREA_REG_CARD_RED_4PLUS"]);});
for(const [name,mutate,pattern] of [
  ["CREA missing lineage",x=>delete x.specification.items[0].sourceResearchEvidenceIds,/Research lineage/],
  ["CREA missing floor",x=>delete x.specification.items[0].settingFloorSemantics,/settingFloorSemantics/],
  ["CREA missing normalization",x=>delete x.specification.items[0].normalizationSemantics,/normalizationSemantics/],
  ["CREA ambiguous Observation",x=>x.specification.items[0].observationIds.push("OBS_BONUS_OUTCOME"),/Observation mapping is not unique/],
  ["CREA missing canonical UI",x=>delete x.specification.items[0].canonicalUi,/canonical UI proof missing/],
  ["CREA missing sharing",x=>delete x.specification.items[0].featureSharing,/Feature\/Evidence sharing proof missing/],
  ["CREA missing one Evidence specification",x=>x.specification.items.pop(),/does not cover every Evidence item/]
])test(name,()=>{const x=creaFixture();mutate(x);assert.throws(()=>compileEvidenceContract(x),pattern);});
test("CREA semantic duplicate fails",()=>{const items=compileEvidenceContract(creaFixture()).evidenceContract.items;assert.throws(()=>assertNoDuplicates([...items,{...items[0],evidenceId:"EVI_DUPLICATE"}]),/DUPLICATE_SEMANTIC_EVIDENCE/);});
test("CREA legacy plus v2 fails atomic cutover",()=>{const x=creaFixture(),migrated=compileEvidenceContract(x);migrated.evidenceUi=x.selection.evidenceUi;assert.throws(()=>buildMachineData(x.research,migrated),/atomic cutover/);});
