import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import {legacyProjection,assertNoDuplicates} from "../tools/lib/evidence-contract-m7.mjs";import {buildMachineData} from "../tools/build-machine-data.mjs";import {compileEvidenceContract} from "../tools/migrate-selection-evidence-contract.mjs";
test("legacy projection preserves IDs, values and unset defaults",()=>{const p=legacyProjection({evidenceUi:{groups:[{groupId:"G",label:"G",selectionMode:"multi",options:[{value:"V",label:"V",allowedSettings:["SET_2"],sourceEvidenceIds:["RE"]}]}]}});assert.equal(p.inputs[0].id,"INP_EVI_G");assert.equal(p.inputs[0].type,"multi_enum");assert.equal(p.items[0].triggerValue,"V");});
test("semantic duplicates fail closed",()=>{const e={evidenceId:"A",sourceResearchEvidenceIds:["RE"],inputId:"I",triggerValue:"V",confirmedSettings:["S"],deniedSettings:[],settingFloorSemantics:"EXACT_ALLOWED_SETTINGS"};assert.throws(()=>assertNoDuplicates([e,{...e,evidenceId:"B"}]),/DUPLICATE_SEMANTIC/);});
test("Hanabi before and after runtime projections are byte-equivalent",()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));const research=read("../research/L_HANABI_KM/research-data.json"),legacy=read("fixtures/evidence-contract-m7/L_HANABI_KM-selection-legacy.json"),migrated=read("../research/L_HANABI_KM/selection-data.json"),stats=read("../research/L_HANABI_KM/statistics-report.json");assert.deepEqual(buildMachineData(research,migrated,stats),buildMachineData(research,legacy,stats));});
test("v2 plus legacy groups cannot materialize simultaneously",()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));const research=read("../research/L_HANABI_KM/research-data.json"),migrated=read("../research/L_HANABI_KM/selection-data.json");migrated.evidenceUi={groups:[{groupId:"DUP",options:[]}]};assert.throws(()=>buildMachineData(research,migrated),/atomic cutover/);});
const migrationFixture=()=>{const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));return{selection:read("fixtures/evidence-contract-m7/L_HANABI_KM-selection-legacy.json"),research:read("../research/L_HANABI_KM/research-data.json"),observation:read("../research/L_HANABI_KM/machine-observation-data.json"),ui:read("../research/L_HANABI_KM/ui-design-data.json"),specification:read("../migration-specs/evidence-contract-m7/L_HANABI_KM.json")};};
for(const [name,mutate,pattern] of [
  ["missing normalization proof",x=>delete x.specification.items[0].normalizationSemantics,/normalizationSemantics proof missing/],
  ["missing setting-floor proof",x=>delete x.specification.items[0].settingFloorSemantics,/settingFloorSemantics proof missing/],
  ["ambiguous Observation proof",x=>x.specification.items[0].observationIds.push("OBS_BONUS_OUTCOME"),/Observation mapping is not unique/],
  ["ambiguous canonical UI placement",x=>x.ui.sections.DUPLICATE={inputIds:["INP_EVI_HANABI_REG_END"]},/canonical UI placement is not unique/],
  ["unproven Feature sharing",x=>delete x.specification.items[0].featureSharing,/Feature\/Evidence sharing proof missing/]
])test(name,()=>{const x=migrationFixture();mutate(x);assert.throws(()=>compileEvidenceContract(x),pattern);});
