import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
const root=path.resolve(new URL("..",import.meta.url).pathname);
test("market snapshot validates",()=>{const r=spawnSync(process.execPath,[path.join(root,"tools","validate-market-snapshot.mjs"),path.join(root,"market-snapshot.json")],{cwd:root,encoding:"utf8"});assert.equal(r.status,0);assert.match(r.stdout,/9機種/);});
test("missing status includes active unmatched market machines",()=>{const r=spawnSync(process.execPath,[path.join(root,"tools","machine-registry-status.mjs"),"--missing"],{cwd:root,encoding:"utf8"});assert.equal(r.status,0);assert.match(r.stdout,/稼働中未収録候補: 8/);assert.match(r.stdout,/Registry 0 \/ Market未紐付け 8/);assert.match(r.stdout,/スマスロ やじきた道中記参る/);});
test("market status separates scheduled machine",()=>{const r=spawnSync(process.execPath,[path.join(root,"tools","machine-registry-status.mjs"),"--market"],{cwd:root,encoding:"utf8"});assert.equal(r.status,0);assert.match(r.stdout,/導入予定未紐付け: 1/);assert.match(r.stdout,/喰霊/);});
test("market merge never invents registry IDs for unmatched machines",()=>{const before=JSON.parse(fs.readFileSync(path.join(root,"machine-registry.json"),"utf8")).machines.length;const r=spawnSync(process.execPath,[path.join(root,"tools","merge-market-snapshot.mjs")],{cwd:root,encoding:"utf8"});assert.equal(r.status,0);const after=JSON.parse(fs.readFileSync(path.join(root,"machine-registry.json"),"utf8")).machines.length;assert.equal(after,before);const report=JSON.parse(fs.readFileSync(path.join(root,"reports","market-registry-merge.json"),"utf8"));assert.equal(report.unmatched.length,9);});
